// হোমিওপ্যাথিক রেফারেন্স ডেটা — ওষুধ, রুব্রিক ও গ্রেড-লিংক।
// এটি একটি নমুনা রেপার্টরি; প্রয়োজনে আরও রুব্রিক/ওষুধ যোগ করা যাবে।
// লিংক-কী ফরম্যাট: "Section > English text" (রুব্রিক টেক্সটের ইংরেজি অংশ, বাংলা বন্ধনী বাদে)।

export const remedies = [
  { name: 'Aconite', source: 'Aconitum napellus', keynotes: 'হঠাৎ তীব্র শুরু, ভয়, অস্থিরতা, শুষ্ক ত্বক, ঠান্ডা শুষ্ক বাতাসে', clinical: 'জ্বর, সর্দি-কাশি, ক্রুপ, ভয়-উদ্বেগ, শ্বাসকষ্ট', better: 'খোলা বাতাস, ঠান্ডা, শান্ত থাকলে', worse: 'শুষ্ক ঠান্ডা বাতাস, রাতে, ভিড়-গরমে' },
  { name: 'Allium cepa', source: 'Allium cepa', keynotes: 'নাক দিয়ে জ্বালাপোড়া পানি, চোখে মিহি পানি, হাঁচি', clinical: 'সর্দি, হাঁচি, চোখের প্রদাহ, অ্যালার্জি', better: 'খোলা বাতাস, ঠান্ডা ঘরে', worse: 'গরম ঘরে, সন্ধ্যায়' },
  { name: 'Alumina', source: 'Alumina', keynotes: 'শুষ্ক ত্বক ও মিউকাস, মল নরম হলেও বেগ কম, ধীর গতি', clinical: 'কোষ্ঠকাঠিন্য, শুষ্ক ত্বক, দুর্বলতা', better: 'ঠান্ডা, খোলা বাতাস', worse: 'গরমে, সকালে' },
  { name: 'Antimonium crud', source: 'Antimonium crudum', keynotes: 'মোটা সাদা জিভ, অতিরিক্ত খাওয়ার পরে, শিশুর ক্রন্দন', clinical: 'পাকস্থলীর সমস্যা, সাদা জিভ, ত্বকের সমস্যা', better: 'বিশ্রাম, খোলা বাতাস', worse: 'অতিরিক্ত খাওয়া, গরমে, ভেজা/স্নানে' },
  { name: 'Antimonium tart', source: 'Antimonium tartaricum', keynotes: 'বুকে কফ জমার শব্দ, দুর্বলতা, বের করতে না পারা', clinical: 'ব্রংকাইটিস, নিউমোনিয়া, বুকে কফ', better: 'কফ বের করলে, উঠে বসলে', worse: 'শুয়ে, রাতে, ঠান্ডায়' },
  { name: 'Apis mellifica', source: 'Apis mellifica', keynotes: 'ফোলা, চিনচিনে ব্যথা, ঠান্ডায় ভালো, তৃষ্ণাহীন', clinical: 'ফোলা, ফোসকা, প্রস্রাব কম, অ্যালার্জি', better: 'ঠান্ডা প্রয়োগ, খোলা বাতাস', worse: 'গরমে, স্পর্শে, রাতে' },
  { name: 'Argentum nitricum', source: 'Argentum nitricum', keynotes: 'পরীক্ষার আগে উদ্বেগ, মিষ্টি খেলে অসুখ, পেট ফাঁপা', clinical: 'উদ্বেগ, ডায়রিয়া, পেট ফাঁপা', better: 'ঠান্ডা বাতাস, ঢেঁকুর তুললে', worse: 'গরমে, রাতে, মিষ্টিতে' },
  { name: 'Arnica montana', source: 'Arnica montana', keynotes: 'আঘাত, কালশিটে, ব্যথা, "আমাকে ছুঁয়ো না"', clinical: 'আঘাত, কালশিটে, পেশি ব্যথা, অস্ত্রোপচার-পরবর্তী', better: 'বিশ্রাম, হালকা চাপে', worse: 'স্পর্শে, নড়াচড়ায়, শুয়ে' },
  { name: 'Arsenicum album', source: 'Arsenicum album', keynotes: 'দাহযন্ত্রণা, অস্থিরতা, মৃত্যুভয়, অল্প অল্প জলপান, ঠান্ডায় বাড়ে', clinical: 'খাদ্যবিষক্রিয়া, ডায়রিয়া, অ্যাজমা, উদ্বেগ', better: 'উষ্ণতা, গরম পানীয়, বিশ্রাম', worse: 'ঠান্ডায়, মাঝরাতে, দুধে' },
  { name: 'Baryta carb', source: 'Baryta carbonica', keynotes: 'ধীর বিকাশ, লজ্জা, বার্ধক্যের দুর্বলতা, গলায় গ্রন্থি', clinical: 'ধীর বিকাশ, টনসিল, বার্ধক্যের দুর্বলতা', better: 'উষ্ণতা, শুয়ে', worse: 'ঠান্ডায়, খোলা বাতাসে' },
  { name: 'Belladonna', source: 'Atropa belladonna', keynotes: 'থাঁচকানো ব্যথা, লাল-গরম মুখ, হঠাৎ শুরু, আলোয় বাড়ে', clinical: 'তীব্র জ্বর, টনসিলিটিস, মাথাব্যথা, প্রদাহ', better: 'শান্ত অন্ধকার ঘর, খাড়া বসলে', worse: 'আলো, শব্দ, নড়াচড়া, স্পর্শ' },
  { name: 'Bellis perennis', source: 'Bellis perennis', keynotes: 'গভীর টিস্যু/স্তনের আঘাত, কালশিটে, ব্যথা', clinical: 'গভীর আঘাত, স্তন/পেটের ক্ষত, কালশিটে', better: 'বিশ্রাম, হালকা চাপে', worse: 'স্পর্শে, নড়াচড়ায়' },
  { name: 'Borax', source: 'Borax', keynotes: 'মুখে ছত্রাক/আলসার, নিচে নামানোয় ভয়, গরমে ঘাম', clinical: 'মুখের আলসার/ছত্রাক, শিশুর পেটের সমস্যা', better: 'গরমে', worse: 'নিচে নামানোয়, ঠান্ডায়, মুখে খাওয়ায়' },
  { name: 'Bryonia', source: 'Bryonia alba', keynotes: 'সামান্য নড়াচড়ায় বাড়ে, শুকনো ঠোঁট, প্রচুর তৃষ্ণা, চাপে ভালো', clinical: 'জ্বর, কাশি, গাঁটের ব্যথা, মাথাব্যথা', better: 'বিশ্রাম, চাপ, ঠান্ডা', worse: 'সামান্য নড়াচড়ায়, গরমে, গভীর শ্বাসে' },
  { name: 'Calcarea carb', source: 'Calcarea carbonica', keynotes: 'ঠান্ডা-ভেজা, ঘাম, ওজন বেশি, সহজে ঠান্ডা লাগে', clinical: 'ওজন বেশি, ঘাম, হাড় দুর্বল, সহজে ঠান্ডা লাগা', better: 'শুষ্ক আবহাওয়া, উষ্ণতা', worse: 'ঠান্ডা-ভেজা, পরিশ্রমে, দুধে' },
  { name: 'Calcarea phos', source: 'Calcarea phosphorica', keynotes: 'হাড় দুর্বল, দেরিতে হাঁটা/দাঁত ওঠা, ক্ষুধা বেশি', clinical: 'হাড়/দাঁত দেরি, রক্তাল্পতা, হজম দুর্বল', better: 'গরমে, খোলা বাতাস', worse: 'ঠান্ডা-ভেজা, আবহাওয়া পরিবর্তনে' },
  { name: 'Calendula', source: 'Calendula officinalis', keynotes: 'ক্ষত নিরাময়, পুঁজ-প্রবণতা, স্থানীয় প্রয়োগে উপকারী', clinical: 'ক্ষত, পুঁজ, কাটা, আলসার', better: 'স্থানীয় প্রয়োগ, শুষ্ক রাখলে', worse: 'ভেজা, সংক্রমণে' },
  { name: 'Cantharis', source: 'Cantharis vesicatoria', keynotes: 'প্রস্রাবে তীব্র জ্বালা, বারবার বেগ, ফোসকা', clinical: 'প্রস্রাবে জ্বালা, সিস্টাইটিস, ফোসকা', better: 'শান্ত থাকলে', worse: 'প্রস্রাবের আগে/পরে, স্পর্শে, কফিতে' },
  { name: 'Carbo veg', source: 'Carbo vegetabilis', keynotes: 'প্রচুর গ্যাস, পেট ফাঁপা, দুর্বলতা, বাতাস খেতে চায়', clinical: 'পেট ফাঁপা, গ্যাস, দুর্বলতা, শক', better: 'বাতাস খেলে, ঢেঁকুর তুললে, ঠান্ডা বাতাস', worse: 'ভেজা আবহাওয়া, খাওয়ার পরে, দুধে' },
  { name: 'Causticum', source: 'Causticum', keynotes: 'প্যারালাইসিস, শুষ্ক কাশি, সহানুভূতিতে কান্না, ঠান্ডা বাতাসে ভালো', clinical: 'প্যারালাইসিস, শুষ্ক কাশি, প্রস্রাব বেরিয়ে যাওয়া, আঁচিল', better: 'ভেজা আবহাওয়া, গরম পানীয়', worse: 'শুষ্ক ঠান্ডা বাতাস, পরিষ্কার আবহাওয়ায়' },
  { name: 'Chamomilla', source: 'Matricaria chamomilla', keynotes: 'খিটখিটে, কোলে নিলে শান্ত, শিশুর দাঁত ওঠা, রাগ', clinical: 'দাঁত ওঠা, খিটখিটে শিশু, কলিক, ব্যথা', better: 'কোলে নিলে, হালকা গরমে', worse: 'রাতে, রাগে, স্পর্শে' },
  { name: 'China', source: 'Chininum officinale', keynotes: 'তরল হারানোর পরে দুর্বলতা, পেট ফাঁপা, ফল খেয়ে পাতলা পায়খানা', clinical: 'দুর্বলতা, রক্ত/তরল হারানো, পেট ফাঁপা, ডায়রিয়া', better: 'চাপে, গরমে, খাওয়ার পরে', worse: 'খোলা বাতাস, স্পর্শে, ফলে' },
  { name: 'Coffea cruda', source: 'Coffea cruda', keynotes: 'অনিদ্রা, মন ছুটছে, আনন্দের পরে ঘুম আসে না', clinical: 'অনিদ্রা, স্নায়ু-উত্তেজনা, ব্যথা', better: 'শান্ত পরিবেশ, বিশ্রাম', worse: 'শব্দ, আনন্দ/উত্তেজনা, কফি' },
  { name: 'Colocynthis', source: 'Citrullus colocynthis', keynotes: 'মোচড়ানো পেট ব্যথা, জোরে চাপলে/কুঁকড়ে ভালো', clinical: 'কলিক, মোচড়ানো পেট ব্যথা, ডায়রিয়া', better: 'জোরে চাপে, কুঁকড়ে, গরমে', worse: 'রাগে, খাওয়ার পরে, ঠান্ডায়' },
  { name: 'Cuprum met', source: 'Cuprum metallicum', keynotes: 'খিল ও মোচড়, নীলাভ রঙ, হঠাৎ তীব্র আক্রমণ', clinical: 'খিল, মৃগী, খসখসে কাশি', better: 'উষ্ণতা, বিশ্রাম', worse: 'ঠান্ডায়, রাতে, স্পর্শে' },
  { name: 'Drosera', source: 'Drosera rotundifolia', keynotes: 'গভীর রাতে কাশির দমক, শ্বাসনালিতে খসখসে শব্দ', clinical: 'ক্রুপ, হুপিং কাশ, গভীর কাশি', better: 'গরমে, খাড়া বসলে', worse: 'শুয়ে, রাতে, কথা বললে' },
  { name: 'Dulcamara', source: 'Solanum dulcamara', keynotes: 'ঠান্ডা-ভেজা আবহাওয়ায় অসুখ, গাঁট ও পেশিতে ব্যথা', clinical: 'ঠান্ডা-ভেজায় অসুখ, গাঁট ব্যথা, চর্মরোগ', better: 'গরমে, শুষ্ক আবহাওয়ায়, নড়াচড়ায়', worse: 'ঠান্ডা-ভেজা, আবহাওয়া পরিবর্তনে' },
  { name: 'Euphrasia', source: 'Euphrasia officinalis', keynotes: 'চোখ থেকে জ্বালাপোড়া পানি, নাকের স্রাব মিহি', clinical: 'চোখের প্রদাহ, সর্দি, কনজংকটিভাইটিস', better: 'খোলা বাতাস, ঠান্ডা', worse: 'গরম ঘরে, রাতে' },
  { name: 'Ferrum met', source: 'Ferrum metallicum', keynotes: 'রক্তাল্পতা, ফ্যাকাশে, দুর্বলতা, সামান্য পরিশ্রমে বাড়ে', clinical: 'রক্তাল্পতা, দুর্বলতা, হজম দুর্বল', better: 'বিশ্রাম, হালকা নড়াচড়া', worse: 'পরিশ্রমে, রাতে, ঠান্ডায়' },
  { name: 'Ferrum phos', source: 'Ferrum phosphoricum', keynotes: 'প্রাথমিক প্রদাহ, হালকা জ্বর, দুর্বলতা, প্রথম স্তরে', clinical: 'প্রাথমিক জ্বর/প্রদাহ, রক্তাল্পতা', better: 'বিশ্রাম', worse: 'রাতে, নড়াচড়ায়' },
  { name: 'Gelsemium', source: 'Gelsemium sempervirens', keynotes: 'দুর্বলতা, কাঁপুনি, ভারী চোখের পাতা, তৃষ্ণাহীন, খারাপ খবরের পরে', clinical: 'ফ্লু, দুর্বলতা, কাঁপুনি, পরীক্ষা-ভয়', better: 'প্রস্রাব করলে, খোলা বাতাস, নড়াচড়ায়', worse: 'ভেজা আবহাওয়া, খারাপ খবরে, ধোঁয়ায়' },
  { name: 'Graphites', source: 'Graphites', keynotes: 'মোটা, ঠান্ডা, চটচটে ত্বকের ক্ষত, কোষ্ঠকাঠিন্য', clinical: 'চর্মরোগ, কোষ্ঠকাঠিন্য, ওজন বেশি', better: 'গরমে, অন্ধকারে', worse: 'ঠান্ডায়, রাতে' },
  { name: 'Hamamelis', source: 'Hamamelis virginiana', keynotes: 'শিরায় রক্তপাত, কালশিটে, আঘাত-পরবর্তী রক্তক্ষরণ', clinical: 'শিরা-ফোলা, রক্তপাত, কালশিটে', better: 'বিশ্রাম, ঠান্ডা প্রয়োগ', worse: 'নড়াচড়ায়, স্পর্শে' },
  { name: 'Hepar sulph', source: 'Hepar sulphuris', keynotes: 'পুঁজ গঠন, অতি সংবেদনশীল, ঠান্ডায় বাড়ে, খোলা বাতাসে অসহ্য', clinical: 'পুঁজ, ফোড়া, টনসিলিটিস, কাশি', better: 'উষ্ণতা, ঢাকা থাকলে, ভেজা আবহাওয়ায়', worse: 'ঠান্ডা খোলা বাতাস, স্পর্শে, শুষ্ক ঠান্ডায়' },
  { name: 'Hydrastis', source: 'Hydrastis canadensis', keynotes: 'ঘন হলুদ আঠালো স্রাব, দুর্বলতা, পেটে খালি ভাব', clinical: 'পাকস্থলীর সমস্যা, ঘন স্রাব, কোষ্ঠকাঠিন্য', better: 'বিশ্রাম, খোলা বাতাস', worse: 'খাওয়ার পরে, ভেজায়' },
  { name: 'Hypericum', source: 'Hypericum perforatum', keynotes: 'স্নাবহুল অংশের আঘাত, বিদ্যুৎ-চমকের মতো ব্যথা', clinical: 'স্নাব-আঘাত, কাটা ক্ষত, বিদ্যুৎ-চমক ব্যথা', better: 'বিশ্রাম, উষ্ণতা', worse: 'স্পর্শে, ঝাঁকুনিতে, ঠান্ডা বাতাসে' },
  { name: 'Hyoscyamus', source: 'Hyoscyamus niger', keynotes: 'সন্দেহ, ঈর্ষা, অশ্লীল আচরণ, রাতে বাড়ে', clinical: 'অস্থিরতা, ঈর্ষা, অনিদ্রা, খিল', better: 'শান্ত পরিবেশ', worse: 'রাতে, শুয়ে, আলোয়' },
  { name: 'Ignatia', source: 'Ignatia amara', keynotes: 'দুঃখ-শোকের পরে, দীর্ঘশ্বাস, গলায় দলা, মেজাজের অস্থিরতা', clinical: 'শোক, হিস্টেরিয়া, গলায় দলা, মাথাব্যথা', better: 'শান্ত থাকলে, চাপে, গভীর শ্বাসে', worse: 'ধোঁয়ায়, খালি পেটে, উত্তেজনায়' },
  { name: 'Iodium', source: 'Iodium', keynotes: 'ক্ষুধা থাকা সত্ত্বেও ওজন কমে, গ্রন্থি ফোলা, গরম অসহ্য', clinical: 'গ্রন্থি ফোলা, ওজন কমা, ক্ষুধা বেশি', better: 'ঠান্ডায়, খোলা বাতাস', worse: 'গরমে, বিশ্রামে' },
  { name: 'Ipecac', source: 'Ipecacuanha', keynotes: 'বমি-বমি ভাব, পরিষ্কার জিভ, নাড়িভুঁড়ি মোচড়', clinical: 'বমি, বমি-বমি ভাব, রক্তপাত, কাশি', better: 'বমি করলে, বিশ্রাম', worse: 'নড়াচড়ায়, গরমে' },
  { name: 'Kali bich', source: 'Kali bichromicum', keynotes: 'ঘন, আঠালো, লম্বা হলুদ স্রাব', clinical: 'সাইনুসাইটিস, ঘন স্রাব, গলা ব্যথা', better: 'গরমে, খোলা বাতাস, চাপে', worse: 'ঠান্ডায়, সকালে, নড়াচড়ায়' },
  { name: 'Kali carb', source: 'Kali carbonicum', keynotes: 'ফোলা, গ্রন্থি, ঠান্ডা, রাত ৩টায় বাড়ে', clinical: 'ফোলা, কাশি, শ্বাসকষ্ট, ঘাম', better: 'উষ্ণতা, খাড়া বসলে', worse: 'ঠান্ডায়, রাত ৩টায়, শুয়ে' },
  { name: 'Kali phos', source: 'Kali phosphoricum', keynotes: 'স্নায়বিক অবসাদ, মাথা খালি ভাব, পরিশ্রম-পরবর্তী', clinical: 'স্নায়বিক অবসাদ, অনিদ্রা, মাথাব্যথা', better: 'বিশ্রাম, খাওয়ার পরে, হালকা নড়াচড়ায়', worse: 'পরিশ্রমে, উত্তেজনায়, রাতে' },
  { name: 'Lachesis', source: 'Lachesis muta', keynotes: 'বেগুনি রঙ, বাম দিক, স্পর্শে অসহ্য, গরমে বাড়ে, কথা বেশি', clinical: 'রক্তসংক্রমণ, গলা ব্যথা, হরমোন সমস্যা', better: 'খোলা বাতাস, ঠান্ডা, কিছু বের হলে', worse: 'গরমে, ঘুমে, আঁটসাঁট পোশাকে, বাম দিকে' },
  { name: 'Ledum', source: 'Ledum palustre', keynotes: 'বিঁধা/ফোঁড়ানো আঘাত, ঠান্ডা প্রয়োগে ভালো', clinical: 'বিঁধা আঘাত, গাঁট ব্যথা, পোকায় কামড়', better: 'ঠান্ডা প্রয়োগ, ঠান্ডা বাতাস', worse: 'গরমে, রাতে, শুয়ে' },
  { name: 'Lycopodium', source: 'Lycopodium clavatum', keynotes: 'ডান দিক, পেট ফাঁপা, আত্মবিশ্বাস কম, বিকাল ৪-৮টায় বাড়ে', clinical: 'পেট ফাঁপা, হজম দুর্বল, আত্মবিশ্বাস কম, কিডনি পাথর', better: 'গরম খাবার, খোলা বাতাস, নড়াচড়ায়', worse: 'বিকাল ৪-৮টা, ঠান্ডা, ডান দিকে' },
  { name: 'Magnesia phos', source: 'Magnesia phosphorica', keynotes: 'খিল ও স্নায়ু-ব্যথা, উষ্ণতা ও চাপে ভালো', clinical: 'খিল, স্নায়ু-ব্যথা, পিরিয়ড ব্যথা', better: 'উষ্ণতা, চাপে, কুঁকড়ে', worse: 'ঠান্ডায়, নড়াচড়ায়, স্পর্শে' },
  { name: 'Merc sol', source: 'Mercurius solubilis', keynotes: 'লালা বেশি, রাতে ঘাম, গরম-ঠান্ডা দুই-ই অসহ্য, কাঁপুনি', clinical: 'টনসিলিটিস, লালা বেশি, ঘাম, আলসার', better: 'মাঝারি তাপমাত্রা', worse: 'রাতে, গরম-ঠান্ডা দুই-তে, শুয়ে' },
  { name: 'Millefolium', source: 'Millefolium', keynotes: 'উজ্জ্বল লাল রক্তপাত, আঘাত-পরবর্তী, ঋতুস্রাব বেশি', clinical: 'রক্তপাত, ঋতুস্রাব বেশি, আঘাত-পরবর্তী', better: 'বিশ্রাম, ঠান্ডা', worse: 'নড়াচড়ায়, গরমে' },
  { name: 'Natrum mur', source: 'Natrum muriaticum', keynotes: 'পুরোনো দুঃখ, একা কাঁদতে চায়, লবণের প্রতি আসক্তি, সূর্যে বাড়ে', clinical: 'দুঃখ, মাথাব্যথা, সর্দি, লবণ আসক্তি', better: 'খোলা বাতাস, বিশ্রাম, ঘামলে', worse: 'সূর্যে, গরমে, সান্ত্বনায়, সমুদ্রে' },
  { name: 'Natrum sulph', source: 'Natrum sulphuricum', keynotes: 'ভেজা আবহাওয়ায় বাড়ে, মাথাব্যথা, জল-সংশ্লিষ্ট অসুখ', clinical: 'ভেজা-আবহাওয়ার অসুখ, মাথাব্যথা, লিভার সমস্যা', better: 'শুষ্ক আবহাওয়া, গরমে, নড়াচড়ায়', worse: 'ভেজা, সকালে, ঠান্ডায়' },
  { name: 'Nitric acid', source: 'Nitricum acidum', keynotes: 'ফাটা ক্ষত, বিঁধুনুনি ব্যথা, কাঠের টুকরোর মতো অনুভূতি', clinical: 'ফাটা ক্ষত, আঁচিল, গলা ব্যথা, রক্তপাত', better: 'উষ্ণতা, বিশ্রাম', worse: 'স্পর্শে, নড়াচড়ায়, রাতে' },
  { name: 'Nux vomica', source: 'Strychnos nux-vomica', keynotes: 'খিটখিটে, অতিরিক্ত কাজ/কফি/মশলা, কোষ্ঠকাঠিন্য, সকালে বাড়ে', clinical: 'হজম সমস্যা, কোষ্ঠকাঠিন্য, খিটখিটে, অতিরিক্ত কাজ', better: 'বিশ্রাম, উষ্ণতা, গভীর শ্বাসে', worse: 'সকালে, খাওয়ার পরে, ঠান্ডায়, মানসিক চাপে' },
  { name: 'Opium', source: 'Opium', keynotes: 'সংবেদনাহীনতা, গভীর ঘুম, কোষ্ঠকাঠিন্য গোলাকার মল, ভয়', clinical: 'কোষ্ঠকাঠিন্য, ঘুম, ভয়, সংবেদনাহীনতা', better: 'গরমে, বিশ্রাম', worse: 'ঠান্ডায়, নড়াচড়ায়' },
  { name: 'Phosphoric acid', source: 'Phosphoricum acidum', keynotes: 'শোক/পরিশ্রম-পরবর্তী অবসাদ, উদাসীনতা, দুর্বল স্মৃতি', clinical: 'অবসাদ, শোক-পরবর্তী, দুর্বল স্মৃতি, ডায়রিয়া', better: 'বিশ্রাম, গরমে, খাওয়ার পরে', worse: 'পরিশ্রমে, মানসিক চাপে, ঠান্ডায়' },
  { name: 'Phosphorus', source: 'Phosphorus', keynotes: 'সহানুভূতিশীল, ঠান্ডা পানি চায়, সহজে রক্তপাত, একা থাকতে ভয়', clinical: 'রক্তপাত, কাশি, ভয়, সহানুভূতি', better: 'ঠান্ডা পানীয়, সঙ্গ, ঘুম, ম্যাসাজ', worse: 'একা, গরমে, বাম দিকে শুয়ে, খালি পেটে' },
  { name: 'Plumbum met', source: 'Plumbum metallicum', keynotes: 'কোষ্ঠকাঠিন্য, প্যারালাইসিস, সংকুচন, ধীর গতি', clinical: 'কোষ্ঠকাঠিন্য, প্যারালাইসিস, খিল', better: 'জোরে চাপে', worse: 'নড়াচড়ায়, স্পর্শে, রাতে' },
  { name: 'Pulsatilla', source: 'Anemone pulsatilla', keynotes: 'মিষ্টস্বভাব, কান্না, পরিবর্তনশীল লক্ষণ, খোলা বাতাসে ভালো, তৃষ্ণাহীন', clinical: 'হরমোন সমস্যা, সর্দি, কান্না, পিরিয়ড অনিয়ম', better: 'খোলা বাতাস, ঠান্ডা, সান্ত্বনা, নড়াচড়া', worse: 'গরম ঘরে, শুয়ে, সন্ধ্যায়, চর্বিযুক্ত খাবারে' },
  { name: 'Rhus tox', source: 'Rhus toxicodendron', keynotes: 'প্রথম নড়াচড়ায় ব্যথা, চলতে থাকলে ভালো, ভেজা আবহাওয়ায় বাড়ে', clinical: 'গাঁট/পেশি ব্যথা, চর্মরোগ, জ্বর', better: 'নড়াচড়া, গরম, খোলা বাতাস', worse: 'প্রথম নড়াচড়ায়, ভেজা-ঠান্ডা, বিশ্রামে, রাতে' },
  { name: 'Ruta graveolens', source: 'Ruta graveolens', keynotes: 'পেশি-টেন্ডন-হাড়ের আবরণের আঘাত, ক্লান্ত ভাব', clinical: 'টেন্ডন/হাড়ের আবরণ আঘাত, চোখের ক্লান্তি', better: 'বিশ্রাম, উষ্ণতা', worse: 'ঠান্ডা-ভেজা, নড়াচড়ায়, শুয়ে' },
  { name: 'Sabina', source: 'Sabina', keynotes: 'উজ্জ্বল লাল রক্তসহ ঋতুস্রাব, নড়াচড়ায় বাড়ে', clinical: 'ঋতুস্রাব বেশি, গর্ভপাত-প্রবণতা, রক্তপাত', better: 'বিশ্রাম, ঠান্ডা', worse: 'নড়াচড়ায়, গরমে, রাতে' },
  { name: 'Sabadilla', source: 'Schoenocaulon officinale', keynotes: 'অবিরাম হাঁচি, ভাবী কল্পনা, নাক চুলকানো', clinical: 'হাঁচি, কৃমি, গলা চুলকানো', better: 'গরমে, খোলা বাতাস', worse: 'ঠান্ডা বাতাস, খালি পেটে' },
  { name: 'Secale cor', source: 'Secale cornutum', keynotes: 'রক্তপাত, শরীর ঠান্ডা অথচ গরম অসহ্য, সংকোচন', clinical: 'রক্তপাত, খিল, সংকোচন', better: 'ঠান্ডা বাতাস, খোলা থাকলে, নড়াচড়ায়', worse: 'গরমে, ঢাকা থাকলে, স্পর্শে' },
  { name: 'Sepia', source: 'Sepia officinalis', keynotes: 'উদাসীনতা, ক্লান্তি, সংসারে অনীহা, নড়াচড়ায় ভালো', clinical: 'হরমোন সমস্যা, ক্লান্তি, উদাসীনতা, পিরিয়ড সমস্যা', better: 'নড়াচড়া, গরমে, বিশ্রাম', worse: 'সকালে, সন্ধ্যায়, ঠান্ডা বাতাস, খালি পেটে' },
  { name: 'Silicea', source: 'Silicea', keynotes: 'দীর্ঘস্থায়ী ক্ষত, পুঁজ, ঠান্ডা সহ্য হয় না, অন্তর্মুখী', clinical: 'পুঁজ, দীর্ঘস্থায়ী ক্ষত, ঘাম, ভয়', better: 'উষ্ণতা, ঢাকা থাকলে, গরম পানীয়', worse: 'ঠান্ডায়, খোলা বাতাস, সকালে' },
  { name: 'Spigelia', source: 'Spigelia anthelmia', keynotes: 'বাম চোখের উপর থাঁচকানো ব্যথা, হৃৎপিণ্ডের অনুভূতি', clinical: 'বাম দিকের মাথাব্যথা, হৃদরোগ, কৃমি', better: 'বিশ্রাম, ডান দিকে শুয়ে, হালকা নড়াচড়ায়', worse: 'নড়াচড়ায়, স্পর্শে, বাম দিকে শুয়ে, সকালে' },
  { name: 'Spongia tosta', source: 'Spongia tosta', keynotes: 'শুষ্ক ক্রুপ কাশি, ভুট্টা-সেঁকার শব্দ, শুয়ে বাড়ে', clinical: 'ক্রুপ, শুষ্ক কাশি, গলা বসা', better: 'গরম পানীয়, খাড়া বসলে', worse: 'শুয়ে, ঠান্ডা বাতাস, কথা বললে' },
  { name: 'Staphysagria', source: 'Staphysagria', keynotes: 'দমন করা রাগ, লজ্জা, অস্ত্রোপচার-পরবর্তী ক্ষত', clinical: 'দমন করা রাগ, অস্ত্রোপচার-পরবর্তী, প্রস্রাব সমস্যা', better: 'বিশ্রাম, গরমে', worse: 'রাগে, স্পর্শে, রাতে' },
  { name: 'Stramonium', source: 'Datura stramonium', keynotes: 'তীব্র ভয়, অন্ধকারে বাড়ে, আলো ও সঙ্গ চায়', clinical: 'তীব্র ভয়, প্রলাপ, খিল, অন্ধকার-ভয়', better: 'আলো, সঙ্গ, গরমে', worse: 'অন্ধকারে, একা, রাতে' },
  { name: 'Sulphur', source: 'Sulphur', keynotes: 'গরম সহ্য হয় না, চুলকানি, লাল ছিদ্র, নোংরা ভাব', clinical: 'চর্মরোগ, চুলকানি, লাল ছিদ্র, গরম অসহ্য', better: 'খোলা বাতাস, শুষ্ক আবহাওয়া', worse: 'গরমে, বিছানার গরমে, স্নানে, রাতে' },
  { name: 'Thuja', source: 'Thuja occidentalis', keynotes: 'আঁচিল, টিকা-পরবর্তী সমস্যা, গোপন ভাব, চর্বিযুক্ত ত্বক', clinical: 'আঁচিল, টিকা-পরবর্তী, চর্বিযুক্ত ত্বক, প্রস্রাব সমস্যা', better: 'শুষ্ক আবহাওয়া, নড়াচড়ায়', worse: 'ভেজা-ঠান্ডা, রাতে, কফিতে' },
  { name: 'Veratrum album', source: 'Veratrum album', keynotes: 'প্রচণ্ড বমি-পায়খানা, ঠান্ডা ঘাম, অবসাদ, অস্থিরতা', clinical: 'প্রচণ্ড বমি-পায়খানা, শক, ঠান্ডা ঘাম', better: 'উষ্ণতা, বিশ্রাম', worse: 'ঠান্ডায়, নড়াচড়ায়, ফলে' },
  { name: 'Zincum met', source: 'Zincum metallicum', keynotes: 'স্নায়বিক ক্লান্তি, পা নাচানো, অস্থিরতা, দুর্বল স্মৃতি', clinical: 'স্নায়বিক ক্লান্তি, অস্থিরতা, খিল, দুর্বল স্মৃতি', better: 'বিশ্রাম, উষ্ণতা', worse: 'নড়াচড়ায়, রাতে, খালি পেটে' },
  { name: 'Aesculus', source: 'Aesculus hippocastanum', keynotes: 'শুকনো অর্শ, পিঠে আড়ষ্ট ব্যথা, মুখে শুষ্ক ভাব', clinical: 'অর্শ, পিঠব্যথা, লিভার সমস্যা', better: 'ঠান্ডায়, খোলা বাতাসে', worse: 'গরমে, নড়াচড়ায়, সকালে' },
  { name: 'Aloe', source: 'Aloe socotrina', keynotes: 'ভোরে পাতলা পায়খানার বেগ, লিভার ভারী, মলদ্বারে শিরা-ফোলা', clinical: 'ডায়রিয়া, লিভার সমস্যা, অর্শ', better: 'ঠান্ডায়', worse: 'সকালে, গরমে, খাওয়ার পরে' },
  { name: 'Ambra grisea', source: 'Ambra grisea', keynotes: 'লজ্জাশীল, সঙ্গ এড়ানো, স্নায়বিক দুর্বলতা, অনিদ্রা', clinical: 'অনিদ্রা, লজ্জা, স্নায়বিক দুর্বলতা', better: 'একা থাকলে, বিশ্রামে', worse: 'সঙ্গে, উত্তেজনায়, কফিতে' },
  { name: 'Anacardium', source: 'Anacardium orientale', keynotes: 'দ্বৈত মনের ভাব, খালি পেটে বাড়ে, খাওয়ার পরে ভালো, স্মৃতি দুর্বল', clinical: 'পাকস্থলীর সমস্যা, দুর্বল স্মৃতি, বাচনিক আচরণ', better: 'খাওয়ার পরে, বিশ্রামে', worse: 'খালি পেটে, সকালে, মানসিক চাপে' },
  { name: 'Aurum met', source: 'Aurum metallicum', keynotes: 'গভীর বিষণ্নতা, আত্মহননের চিন্তা, দায়িত্ববোধ, হৃদরোগ', clinical: 'বিষণ্নতা, হৃদরোগ, উচ্চ রক্তচাপ', better: 'খোলা বাতাসে, সন্ধ্যায়, হালকা নড়াচড়ায়', worse: 'রাতে, গরমে, বিরোধে' },
  { name: 'Baptisia', source: 'Baptisia tinctoria', keynotes: 'বিষণ্ণ মাতাল ভাব, দুর্গন্ধযুক্ত স্রাব, দ্রুত অবসাদ, জিভ কাঁচা মাংসের মতো', clinical: 'টাইফয়েড-জাতীয় জ্বর, সংক্রমণ, দুর্গন্ধ', better: 'বিশ্রামে, খাড়া বসলে', worse: 'নড়াচড়ায়, শুয়ে, ভোরে' },
  { name: 'Cactus', source: 'Cactus grandiflorus', keynotes: 'হৃদযন্ত্রে লোহার বর্মের মতো সংকোচন, বাম বাহুতে ব্যথা', clinical: 'হৃদরোগ, বুকে সংকোচন, রক্তচাপ', better: 'খোলা বাতাসে, বিশ্রামে', worse: 'নড়াচড়ায়, রাতে, বাম দিকে শুয়ে' },
  { name: 'Camphora', source: 'Camphora', keynotes: 'শরীর হিমশীতল অথচ ঢাকা সহ্য হয় না, অবসাদ, বিস্মৃতি', clinical: 'শক, হিমশীতল অবসাদ, কলেরা-জাতীয় অবস্থা', better: 'খোলা থাকলে', worse: 'ঢাকা থাকলে, ঠান্ডা বাতাসে, রাতে' },
  { name: 'Capsicum', source: 'Capsicum annuum', keynotes: 'জ্বালাপোড়া, লাল ফোলা, কানের পেছনে ব্যথা, শীতে কাঁপুনি', clinical: 'গলাব্যথা, কানব্যথা, প্রস্রাবে জ্বালা', better: 'উষ্ণতা, গরম পানীয়', worse: 'ঠান্ডায়, খোলা বাতাসে, নড়াচড়ায়' },
  { name: 'Carbo animalis', source: 'Carbo animalis', keynotes: 'গ্রন্থি শক্ত-ফোলা, নীলাভ ঠান্ডা অংশ, ধীর দুর্বলতা', clinical: 'গ্রন্থি ফোলা, শক্ত ফোড়া, দুর্বলতা', better: 'খোলা বাতাসে, ঠান্ডায়', worse: 'গরমে, সন্ধ্যায়, স্পর্শে' },
  { name: 'Chelidonium', source: 'Chelidonium majus', keynotes: 'ডান দিকে লিভার ব্যথা, কাঁধের ফলকের নিচে ব্যথা, তেতো মুখ', clinical: 'লিভার/পিত্তথলি, জন্ডিস, ডান দিকের ব্যথা', better: 'গরম খাবার, ডান দিকে শুয়ে, চাপে', worse: 'নড়াচড়ায়, ভোরে, আবহাওয়া পরিবর্তনে' },
  { name: 'Cina', source: 'Cina maritima', keynotes: 'কৃমি, নাক চুলকানো, খিটখিটে শিশু, কোলে নিলেও শান্ত হয় না', clinical: 'কৃমি, খিটখিটে শিশু, পেটব্যথা', better: 'উপুড় শুয়ে, চাপে', worse: 'রাতে, স্পর্শে, মিষ্টিতে' },
  { name: 'Cimicifuga', source: 'Cimicifuga racemosa', keynotes: 'মেরুদণ্ডে তীরের মতো ব্যথা, পিরিয়ডে তীব্র কষ্ট, মেঘলা দিনে বাড়ে', clinical: 'পিরিয়ড ব্যথা, মেরুদণ্ড ব্যথা, বিষণ্নতা', better: 'গরমে, বিশ্রামে', worse: 'মেঘলা দিনে, ঠান্ডায়, পিরিয়ডের সময়' },
  { name: 'Conium', source: 'Conium maculatum', keynotes: 'গ্রন্থি শক্ত, দুর্বলতা নিচ থেকে উপরে ওঠে, মনোযোগে কষ্ট', clinical: 'শক্ত গ্রন্থি, দুর্বলতা, কাঁপুনি', better: 'নড়াচড়ায়, অন্ধকারে, একা', worse: 'বিশ্রামে, শুয়ে, আবহাওয়া পরিবর্তনে' },
  { name: 'Digitalis', source: 'Digitalis purpurea', keynotes: 'ধীর অনিয়মিত নাড়ি, হৃদয় থমকে যাওয়ার ভয়, ডান দিকে শুলে শ্বাসকষ্ট', clinical: 'হৃদরোগ, ধীর নাড়ি, লিভার সমস্যা', better: 'খাড়া বসলে, বাম দিকে শুয়ে', worse: 'নড়াচড়ায়, ডান দিকে শুয়ে, রাতে' },
  { name: 'Dioscorea', source: 'Dioscorea villosa', keynotes: 'প্রসারিত করলে ভালো — খিল ও পেটব্যথা, আঙুল ছড়িয়ে উপকার', clinical: 'কলিক, খিল, স্নায়ু-ব্যথা', better: 'প্রসারিত করলে, খোলা বাতাসে', worse: 'কুঁকড়ে, বসে, সকালে' },
  { name: 'Eupatorium perf', source: 'Eupatorium perfoliatum', keynotes: 'হাড় ভাঙার মতো ব্যথা, তৃষ্ণা, কাঁপুনি ভোর ৭-৯টা', clinical: 'ফ্লু/জ্বর, হাড়ের ব্যথা', better: 'বমি করলে, ঘামলে, বিশ্রামে', worse: 'নড়াচড়ায়, ভোরে, ঠান্ডায়' },
  { name: 'Fluoric acid', source: 'Fluoricum acidum', keynotes: 'ফিসচুলা, দীর্ঘস্থায়ী পুঁজ, আনন্দময় মেজাজ, গরমে বাড়ে', clinical: 'ফিসচুলা, আলসার, দাঁতের ক্ষয়', better: 'ঠান্ডায়, খোলা বাতাসে', worse: 'গরমে, সন্ধ্যায়, বিশ্রামে' },
  { name: 'Glonoinum', source: 'Glonoinum', keynotes: 'রোদে মাথাব্যথা, মাথায় রক্ত ছুটে ওঠা, ঢেউয়ের মতো অনুভূতি', clinical: 'সানস্ট্রোক, রক্তচাপ, মাথাব্যথা', better: 'ঠান্ডায়, অন্ধকারে, খোলা বাতাসে', worse: 'রোদে, গরমে, নড়াচড়ায়' },
  { name: 'Kali brom', source: 'Kali bromatum', keynotes: 'অস্থির হাত, স্মৃতিভ্রম, মুখে ব্রণ, অনিদ্রা', clinical: 'অস্থিরতা, অনিদ্রা, ব্রণ', better: 'নড়াচড়ায়, কাজে মন দিলে', worse: 'রাতে, বিশ্রামে' },
  { name: 'Kali mur', source: 'Kali muriaticum', keynotes: 'সাদা ঘন স্রাব, গ্রন্থি ফোলা, জিভে সাদা প্রলেপ, দ্বিতীয় স্তরের প্রদাহ', clinical: 'সাদা স্রাব, গ্রন্থি ফোলা, প্রদাহ', better: 'খোলা বাতাসে, নড়াচড়ায়', worse: 'চর্বিযুক্ত খাবারে, গরমে, সকালে' },
  { name: 'Kali sulph', source: 'Kali sulphuricum', keynotes: 'হলুদ আঠালো স্রাব, প্রদাহের শেষ স্তর, গরম ঘরে বাড়ে', clinical: 'হলুদ স্রাব, চর্মরোগের শেষ স্তর', better: 'ঠান্ডা খোলা বাতাসে', worse: 'গরমে, সন্ধ্যায়, গরম ঘরে' },
  { name: 'Kreosote', source: 'Kreosotum', keynotes: 'দাঁতে দ্রুত ক্ষয়, জ্বালাপোড়া স্রাব, শিশুর মাথা ঘামে', clinical: 'দাঁতের সমস্যা, শ্বেতস্রাব, শিশুর অস্থিরতা', better: 'নড়াচড়ায়, গরমে', worse: 'বিশ্রামে, রাতে, ঠান্ডায়' },
  { name: 'Lac defloratum', source: 'Lac defloratum', keynotes: 'মাইগ্রেন, কোষ্ঠকাঠিন্য, দুধে বিতৃষ্ণা', clinical: 'মাইগ্রেন, কোষ্ঠকাঠিন্য, স্তন সমস্যা', better: 'শান্ত থাকলে, চাপে', worse: 'নড়াচড়ায়, সকালে, দুধে' },
  { name: 'Lilium tigrinum', source: 'Lilium tigrinum', keynotes: 'নিচের দিকে চাপ ভাব, তড়িঘড়ি, হৃদয় ও স্ত্রী-অঙ্গের লক্ষণ', clinical: 'স্ত্রী-রোগ, হৃৎকম্পন, খিটখিটে মেজাজ', better: 'খোলা বাতাসে, নড়াচড়ায়', worse: 'গরমে, দুপুরে, বিশ্রামে' },
  { name: 'Mag carb', source: 'Magnesia carbonica', keynotes: 'খিটখিটে শিশু, দুধ হজম হয় না, পেটে মোচড় ও খিল', clinical: 'শিশুর পাকস্থলী সমস্যা, খিল, দাঁত ওঠা', better: 'নড়াচড়ায়, খোলা বাতাসে, চাপে', worse: 'রাতে, দুধে, বিশ্রামে' },
  { name: 'Natrum phos', source: 'Natrum phosphoricum', keynotes: 'অম্বল, টক ঢেঁকুর, মধুর রঙের পাতলা পায়খানা, কৃমি', clinical: 'অ্যাসিডিটি, কৃমি, গাঁট ব্যথা', better: 'শুষ্ক আবহাওয়ায়, নড়াচড়ায়', worse: 'ভেজায়, দুধে, মিষ্টিতে' },
  { name: 'Petroleum', source: 'Petroleum', keynotes: 'শীতে হাত-পা ফাটে, গাড়িতে বমি ভাব, ত্বক মোমের মতো', clinical: 'ত্বক ফাটা, গাড়ি-বমি, চর্মরোগ', better: 'খাওয়ার পরে, গরমে, নড়াচড়ায়', worse: 'শীতে, রাতে, গাড়িতে' },
  { name: 'Phytolacca', source: 'Phytolacca decandra', keynotes: 'গলায় গরম বস্তুর অনুভূতি, স্তনে শক্ত গুলি, গ্রন্থি ফোলা', clinical: 'গলাব্যথা, স্তন প্রদাহ, গাঁট ব্যথা', better: 'গরম পানীয়, বিশ্রামে', worse: 'ঠান্ডা পানীয়, ভেজায়, রাতে' },
  { name: 'Podophyllum', source: 'Podophyllum peltatum', keynotes: 'প্রচণ্ড পাতলা পায়খানা ভোরে, মলদ্বার বেরিয়ে আসার ভাব', clinical: 'ডায়রিয়া, লিভার, দাঁত ওঠা', better: 'উপুড় শুয়ে, চাপে', worse: 'ভোরে, গরমে, নড়াচড়ায়' },
  { name: 'Psorinum', source: 'Psorinum', keynotes: 'অত্যন্ত শীতপ্রবণ, দুর্গন্ধযুক্ত স্রাব, হতাশা, নোংরা ত্বক', clinical: 'পুরোনো চর্মরোগ, দুর্গন্ধ, হতাশা', better: 'উষ্ণতা, গরম পানীয়', worse: 'ঠান্ডায়, স্নানে, বাম দিকে শুয়ে' },
  { name: 'Pyrogenium', source: 'Pyrogenium', keynotes: 'পুঁজ-সংক্রমণ, নাড়ি ও তাপমাত্রার অমিল, বিছানা শক্ত মনে হয়', clinical: 'সেপসিস, জ্বর, পুঁজ', better: 'নড়াচড়ায়, গরমে', worse: 'বিশ্রামে, ঠান্ডায়, শুয়ে' },
  { name: 'Sanguinaria', source: 'Sanguinaria canadensis', keynotes: 'ডান দিকের মাইগ্রেন, মাথা গরম-পা ঠান্ডা, ঘুমালে ভালো', clinical: 'ডান মাইগ্রেন, মেনোপজ, কাশি', better: 'শুয়ে, ঘুমালে, ঢেঁকুর তুললে', worse: 'নড়াচড়ায়, রোদে, গরমে' },
  { name: 'Sarsaparilla', source: 'Sarsaparilla', keynotes: 'প্রস্রাবের শেষে তীব্র ব্যথা, বালু পড়া, বাম স্তনে ব্যথা', clinical: 'প্রস্রাবের পাথর, চর্মরোগ, স্তন ব্যথা', better: 'নড়াচড়ায়, খোলা বাতাসে', worse: 'রাতে, ভেজায়, প্রস্রাবের সময়' },
  { name: 'Senega', source: 'Senega officinalis', keynotes: 'বুকে কফ জমে বের না হওয়া, মাথা নাড়লে লক্ষণ বাড়ে', clinical: 'ব্রংকাইটিস, চোখের ক্লান্তি, গলাব্যথা', better: 'খাওয়ার পরে, বিশ্রামে', worse: 'নড়াচড়ায়, মাথা নাড়লে, সকালে' },
  { name: 'Squilla', source: 'Squilla maritima', keynotes: 'কাশির সাথে প্রস্রাব, মুখে হাত দেওয়া, ঘন ঘন হাঁচি', clinical: 'কাশি, শ্বাসকষ্ট, হাঁচি', better: 'বিশ্রামে', worse: 'নড়াচড়ায়, ঠান্ডায়, সকালে' },
  { name: 'Stannum met', source: 'Stannum metallicum', keynotes: 'গভীর অবসাদ, বুকে খালি ভাব, কথায় দুর্বল, দীর্ঘস্থায়ী কাশি', clinical: 'দুর্বলতা, দীর্ঘস্থায়ী কাশি, স্নায়ু-অবসাদ', better: 'বিশ্রামে, চাপে', worse: 'পরিশ্রমে, ঠান্ডায়, সন্ধ্যায়' },
  { name: 'Tabacum', source: 'Tabacum', keynotes: 'মৃত্যুবৎ বমি ভাব, ঠান্ডা ঘাম, মুখ ফ্যাকাশে, সামান্য নড়াচড়ায় বাড়ে', clinical: 'বমি, গাড়ি-অসুখ, শক', better: 'খোলা বাতাসে, জামা খুললে, বিশ্রামে', worse: 'নড়াচড়ায়, চোখ খুললে, গরমে' },
  { name: 'Tarentula', source: 'Tarentula hispanica', keynotes: 'অস্থির শিশু, সঙ্গীত ভালোবাসে, দ্রুত হাত-পা নাচানো', clinical: 'শিশুর অস্থিরতা, খিল, অনিদ্রা', better: 'সঙ্গীতে, নড়াচড়ায়', worse: 'বিরক্তিতে, স্পর্শে, একা' },
  { name: 'Tuberculinum', source: 'Tuberculinum bovinum', keynotes: 'বারবার ঠান্ডা লাগা, পরিবর্তনের আকাঙ্ক্ষা, চিকন শিশু, রাতে ঘাম', clinical: 'বারবার সংক্রমণ, কাশি, রাতে ঘাম', better: 'খোলা বাতাসে, পরিবর্তনে, নড়াচড়ায়', worse: 'বদ্ধ ঘরে, সন্ধ্যায়, দুধে' },
];

// প্রতিটি রুব্রিক: { section, text }
export const rubrics = [
  // MIND
  { section: 'Mind', text: 'Anxiety (উদ্বেগ)' },
  { section: 'Mind', text: 'Fear of death (মৃত্যুভয়)' },
  { section: 'Mind', text: 'Restlessness (অস্থিরতা)' },
  { section: 'Mind', text: 'Irritability (খিটখিটে মেজাজ)' },
  { section: 'Mind', text: 'Grief, ailments from (শোকের পরে)' },
  { section: 'Mind', text: 'Weeping, consolation agg. (সান্ত্বনায় বাড়ে)' },
  { section: 'Mind', text: 'Delirium (প্রলাপ)' },
  { section: 'Mind', text: 'Forgetfulness (ভুলে যাওয়া)' },
  { section: 'Mind', text: 'Ailments from anger (রাগের পরে)' },
  { section: 'Mind', text: 'Consolation amel. (সান্ত্বনায় ভালো)' },
  { section: 'Mind', text: 'Loquacity (বেশি কথা)' },
  { section: 'Mind', text: 'Suspicion (সন্দেহ)' },
  { section: 'Mind', text: 'Aversion to company (সঙ্গবিমুখতা)' },
  { section: 'Mind', text: 'Desire for company (সঙ্গপ্রিয়)' },
  { section: 'Mind', text: 'Sadness, melancholy (বিষণ্নতা)' },
  { section: 'Mind', text: 'Fear, being alone (একা থাকার ভয়)' },

  // HEAD
  { section: 'Head', text: 'Pain, throbbing (থাঁচকানো মাথাব্যথা)' },
  { section: 'Head', text: 'Pain from light (আলোয় বাড়ে)' },
  { section: 'Head', text: 'Pain, better cold application (ঠান্ডায় ভালো)' },
  { section: 'Head', text: 'Vertigo (মাথা ঘোরা)' },
  { section: 'Head', text: 'Pain, stitching (বিঁধুনুনি ব্যথা)' },
  { section: 'Head', text: 'Pain, better warmth (উষ্ণতায় ভালো)' },
  { section: 'Head', text: 'Headache, one-sided left (বাম দিকের মাথাব্যথা)' },
  { section: 'Head', text: 'Headache, one-sided right (ডান দিকের মাথাব্যথা)' },
  { section: 'Head', text: 'Headache from sun or heat (রোদে/গরমে মাথাব্যথা)' },
  { section: 'Head', text: 'Headache, better sleep (ঘুমালে মাথাব্যথা ভালো)' },

  // EYE
  { section: 'Eye', text: 'Inflammation, redness (চোখ লাল, প্রদাহ)' },
  { section: 'Eye', text: 'Lachrymation (চোখ দিয়ে পানি)' },
  { section: 'Eye', text: 'Photophobia (আলো-অসহিষ্ণুতা)' },
  { section: 'Eye', text: 'Eyes, burning (চোখে জ্বালা)' },

  // EAR
  { section: 'Ear', text: 'Earache (কানব্যথা)' },
  { section: 'Ear', text: 'Ear, discharge (কান দিয়ে স্রাব)' },
  { section: 'Ear', text: 'Noises, ringing (কানে ঝিনঝিন)' },

  // NOSE
  { section: 'Nose', text: 'Coryza, bland discharge (মিহি স্রাব)' },
  { section: 'Nose', text: 'Coryza, acrid discharge (জ্বালাপোড়া স্রাব)' },
  { section: 'Nose', text: 'Discharge, thick stringy (ঘন আঠালো স্রাব)' },
  { section: 'Nose', text: 'Discharge, yellow (হলুদ স্রাব)' },
  { section: 'Nose', text: 'Sneezing, frequent (ঘন ঘন হাঁচি)' },
  { section: 'Nose', text: 'Nosebleed (নাক দিয়ে রক্ত)' },
  { section: 'Nose', text: 'Smell, loss of (ঘ্রাণহানি)' },

  // MOUTH
  { section: 'Mouth', text: 'Tongue, coated white (জিভে সাদা প্রলেপ)' },
  { section: 'Mouth', text: 'Tongue, dry (শুকনো জিভ)' },
  { section: 'Mouth', text: 'Taste, bitter (তেতো স্বাদ)' },
  { section: 'Mouth', text: 'Lips, cracked (ঠোঁট ফাটা)' },
  { section: 'Mouth', text: 'Mouth, ulcers (মুখে আলসার)' },

  // TEETH
  { section: 'Teeth', text: 'Toothache, better cold (ঠান্ডায় দাঁতব্যথা ভালো)' },
  { section: 'Teeth', text: 'Toothache, worse warmth (গরমে দাঁতব্যথা বাড়ে)' },
  { section: 'Teeth', text: 'Teeth, grinding (দাঁত কিড়মিড়)' },

  // FACE
  { section: 'Face', text: 'Face red, hot (মুখ লাল-গরম)' },

  // THROAT
  { section: 'Throat', text: 'Sore throat, better cold drinks (ঠান্ডা পানে ভালো)' },
  { section: 'Throat', text: 'Pain, stinging (চিনচিনে ব্যথা)' },
  { section: 'Throat', text: 'Throat, dry (গলা শুকনো)' },
  { section: 'Throat', text: 'Swallowing, painful (গিলতে ব্যথা)' },
  { section: 'Throat', text: 'Throat, raw scraping (গলা কাঁচা-খসখসে)' },

  // STOMACH
  { section: 'Stomach', text: 'Nausea (বমি ভাব)' },
  { section: 'Stomach', text: 'Thirst, extreme (প্রচণ্ড তৃষ্ণা)' },
  { section: 'Stomach', text: 'Thirstless (তৃষ্ণাহীন)' },
  { section: 'Stomach', text: 'Vomiting (বমি)' },
  { section: 'Stomach', text: 'Appetite loss (ক্ষুধামান্দ্য)' },
  { section: 'Stomach', text: 'Craving, salt (লবণের ঝোঁক)' },
  { section: 'Stomach', text: 'Craving, sweets (মিষ্টির ঝোঁক)' },
  { section: 'Stomach', text: 'Aversion to food (খাদ্যে অনীহা)' },
  { section: 'Stomach', text: 'Hiccough (হেঁচকি)' },
  { section: 'Stomach', text: 'Eructations, sour (টক ঢেঁকুর)' },
  { section: 'Stomach', text: 'Stomach, empty feeling (পেটে খালি ভাব)' },
  { section: 'Stomach', text: 'Nausea not relieved by vomiting (বমি করলেও বমি ভাব কমে না)' },

  // ABDOMEN
  { section: 'Abdomen', text: 'Flatulence, bloating (পেট ফাঁপা, গ্যাস)' },
  { section: 'Abdomen', text: 'Pain, colic (মোচড়ানো পেটব্যথা)' },
  { section: 'Abdomen', text: 'Pain, better bending double (কুঁকড়ে ভালো)' },
  { section: 'Abdomen', text: 'Pain, better stretching (প্রসারিত করলে ভালো)' },
  { section: 'Abdomen', text: 'Liver, sore and enlarged (লিভার ফোলা-ব্যথা)' },

  // RECTUM
  { section: 'Rectum', text: 'Diarrhoea (পাতলা পায়খানা)' },
  { section: 'Rectum', text: 'Constipation (কোষ্ঠকাঠিন্য)' },
  { section: 'Rectum', text: 'Diarrhoea from fruit (ফল খেয়ে পায়খানা)' },
  { section: 'Rectum', text: 'Stool, ineffectual urging (বারবার বেগ, নিষ্ফল)' },
  { section: 'Rectum', text: 'Stool, hard lumps (শক্ত গোলাকার মল)' },
  { section: 'Rectum', text: 'Bleeding piles (রক্তসহ অর্শ)' },
  { section: 'Rectum', text: 'Diarrhoea, morning (ভোরে পাতলা পায়খানা)' },
  { section: 'Rectum', text: 'Worms (কৃমি)' },
  { section: 'Rectum', text: 'Piles, burning (অর্শে জ্বালা)' },
  { section: 'Rectum', text: 'Stool, offensive (দুর্গন্ধযুক্ত মল)' },

  // URINE
  { section: 'Urine', text: 'Urine, burning (প্রস্রাবে জ্বালা)' },
  { section: 'Urine', text: 'Urine, frequent urging (বারবার প্রস্রাবের বেগ)' },
  { section: 'Urine', text: 'Urine, scanty (অল্প প্রস্রাব)' },
  { section: 'Urine', text: 'Urine, stone and gravel (প্রস্রাবে পাথর/বালু)' },
  { section: 'Urine', text: 'Urine, involuntary (প্রস্রাব বেরিয়ে যাওয়া)' },

  // RESPIRATION
  { section: 'Respiration', text: 'Breathing, difficult (শ্বাসকষ্ট)' },
  { section: 'Respiration', text: 'Breathing, better open air (খোলা বাতাসে ভালো)' },
  { section: 'Respiration', text: 'Breath, short (ছোট শ্বাস)' },

  // COUGH
  { section: 'Cough', text: 'Cough, dry (শুকনো কাশি)' },
  { section: 'Cough', text: 'Cough, loose rattling (কফসহ ঘড়ঘড় শব্দ)' },
  { section: 'Cough', text: 'Cough, worse at night (রাতে বাড়ে)' },
  { section: 'Cough', text: 'Cough, croupy barking (ক্রুপ-জাতীয় কাশি)' },
  { section: 'Cough', text: 'Cough, better warmth (উষ্ণতায় ভালো)' },
  { section: 'Cough', text: 'Cough, with expectoration (কফ ওঠা কাশি)' },
  { section: 'Cough', text: 'Cough, worse cold air (ঠান্ডা বাতাসে কাশি বাড়ে)' },
  { section: 'Cough', text: 'Cough, with involuntary urination (কাশির সাথে প্রস্রাব বেরিয়ে যাওয়া)' },

  // CHEST
  { section: 'Chest', text: 'Oppression of chest (বুকে চাপ)' },
  { section: 'Chest', text: 'Palpitation (হৃৎকম্পন)' },
  { section: 'Chest', text: 'Chest, heart pain (হৃদযন্ত্রের ব্যথা)' },
  { section: 'Chest', text: 'Chest, constriction (বুকে সংকোচন)' },

  // BACK
  { section: 'Back', text: 'Backache, better from motion (নড়লে ভালো)' },
  { section: 'Back', text: 'Backache, worse sitting (বসে থাকলে বাড়ে)' },

  // EXTREMITIES
  { section: 'Extremities', text: 'Joint pain, better continued motion (চালিয়ে নড়লে ভালো)' },
  { section: 'Extremities', text: 'Cramps, calves (পায়ের খিল ধরা)' },
  { section: 'Extremities', text: 'Hands, cold (ঠান্ডা হাত)' },
  { section: 'Extremities', text: 'Feet, cold (ঠান্ডা পা)' },
  { section: 'Extremities', text: 'Trembling, hands (হাত কাঁপা)' },
  { section: 'Extremities', text: 'Pain, bones (হাড়ের ব্যথা)' },
  { section: 'Extremities', text: 'Cramps, better stretching (প্রসারিত করলে খিল ভালো)' },
  { section: 'Extremities', text: 'Pain, shifting (ব্যথা এদিক-ওদিক ঘোরে)' },

  // SLEEP
  { section: 'Sleep', text: 'Sleeplessness (অনিদ্রা)' },
  { section: 'Sleep', text: 'Dreams, anxious (দুঃস্বপ্ন)' },
  { section: 'Sleep', text: 'Sleepiness, daytime (দিনে ঘুমঘুম ভাব)' },
  { section: 'Sleep', text: 'Waking, early (ভোরে জেগে ওঠা)' },
  { section: 'Sleep', text: 'Sleeplessness from thoughts (চিন্তায় অনিদ্রা)' },
  { section: 'Sleep', text: 'Sleeplessness, children (শিশুর অনিদ্রা)' },

  // FEVER
  { section: 'Fever', text: 'Fever with thirst (তৃষ্ণাসহ জ্বর)' },
  { section: 'Fever', text: 'Chill, shivering (কাঁপুনি)' },
  { section: 'Fever', text: 'Heat, burning (দাহযুক্ত জ্বর)' },
  { section: 'Fever', text: 'Sweat, profuse (প্রচুর ঘাম)' },
  { section: 'Fever', text: 'Sweat, night (রাতে ঘাম)' },

  // SKIN
  { section: 'Skin', text: 'Urticaria, hives (আমবাত, চাকতি ফুসকুড়ি)' },
  { section: 'Skin', text: 'Boils, abscess (ফোঁড়া, পুঁজ)' },
  { section: 'Skin', text: 'Eruptions, itching (চুলকানি)' },
  { section: 'Skin', text: 'Warts (আঁচিল)' },
  { section: 'Skin', text: 'Skin, dry (শুকনো ত্বক)' },
  { section: 'Skin', text: 'Bruises easily (সহজে কালশিটে)' },
  { section: 'Skin', text: 'Eruptions, cracking (ত্বক ফাটা)' },
  { section: 'Skin', text: 'Ulcers, chronic (দীর্ঘস্থায়ী ক্ষত)' },
  { section: 'Skin', text: 'Sweat, offensive (দুর্গন্ধযুক্ত ঘাম)' },

  // FEMALE
  { section: 'Female', text: 'Menses, too early (ঋতুস্রাব আগে)' },
  { section: 'Female', text: 'Menses, too late (ঋতুস্রাব দেরিতে)' },
  { section: 'Female', text: 'Menses, profuse (অতিরিক্ত ঋতুস্রাব)' },
  { section: 'Female', text: 'Menses, painful (তীব্র কষ্টদায়ক ঋতুস্রাব)' },
  { section: 'Female', text: 'Leucorrhoea (শ্বেতস্রাব)' },

  // GENERALITIES
  { section: 'Generalities', text: 'Injury, bruises (আঘাত, কালশিটে)' },
  { section: 'Generalities', text: 'Wounds, punctured (বিঁধা ক্ষত)' },
  { section: 'Generalities', text: 'Weakness, prostration (দুর্বলতা, অবসাদ)' },
  { section: 'Generalities', text: 'Better from cold (ঠান্ডায় ভালো)' },
  { section: 'Generalities', text: 'Worse from cold, damp (ঠান্ডা-ভেজায় বাড়ে)' },
  { section: 'Generalities', text: 'Worse from heat (গরমে বাড়ে)' },
  { section: 'Generalities', text: 'Better from motion (নড়াচড়ায় ভালো)' },
  { section: 'Generalities', text: 'Worse from motion (নড়াচড়ায় বাড়ে)' },
  { section: 'Generalities', text: 'Better from warmth (উষ্ণতায় ভালো)' },
  { section: 'Generalities', text: 'Worse evening or night (সন্ধ্যা/রাতে বাড়ে)' },
  { section: 'Generalities', text: 'Worse morning (সকালে বাড়ে)' },
  { section: 'Generalities', text: 'Food poisoning (খাদ্যবিষক্রিয়া)' },
  { section: 'Generalities', text: 'Sepsis, pus formation (পুঁজ-সংক্রমণ)' },
  { section: 'Generalities', text: 'Better from pressure (চাপে ভালো)' },
  { section: 'Generalities', text: 'Worse from cold wind (ঠান্ডা বাতাসে বাড়ে)' },
];

// লিংক: rubric (section > text), remedy name, grade (১-৩)
export const links = [
  // MIND
  ['Mind > Anxiety', 'Aconite', 3], ['Mind > Anxiety', 'Arsenicum album', 3],
  ['Mind > Anxiety', 'Argentum nitricum', 3], ['Mind > Anxiety', 'Phosphorus', 3],
  ['Mind > Anxiety', 'Gelsemium', 2], ['Mind > Anxiety', 'Ignatia', 2],
  ['Mind > Anxiety', 'Pulsatilla', 2], ['Mind > Anxiety', 'Chamomilla', 2],
  ['Mind > Fear of death', 'Aconite', 3], ['Mind > Fear of death', 'Arsenicum album', 3],
  ['Mind > Fear of death', 'Phosphorus', 2], ['Mind > Fear of death', 'Gelsemium', 1],
  ['Mind > Restlessness', 'Aconite', 3], ['Mind > Restlessness', 'Arsenicum album', 3],
  ['Mind > Restlessness', 'Rhus tox', 3], ['Mind > Restlessness', 'Chamomilla', 2],
  ['Mind > Restlessness', 'Zincum met', 2],
  ['Mind > Irritability', 'Nux vomica', 3], ['Mind > Irritability', 'Chamomilla', 3],
  ['Mind > Irritability', 'Bryonia', 2], ['Mind > Irritability', 'Sepia', 2],
  ['Mind > Irritability', 'Hepar sulph', 2], ['Mind > Irritability', 'Lycopodium', 1],
  ['Mind > Grief, ailments from', 'Ignatia', 3], ['Mind > Grief, ailments from', 'Natrum mur', 3],
  ['Mind > Grief, ailments from', 'Pulsatilla', 2], ['Mind > Grief, ailments from', 'Phosphoric acid', 2],
  ['Mind > Weeping, consolation agg.', 'Natrum mur', 3], ['Mind > Weeping, consolation agg.', 'Silicea', 2],
  ['Mind > Weeping, consolation agg.', 'Sepia', 2], ['Mind > Weeping, consolation agg.', 'Ignatia', 2],
  ['Mind > Delirium', 'Belladonna', 3], ['Mind > Delirium', 'Hyoscyamus', 3],
  ['Mind > Delirium', 'Stramonium', 2], ['Mind > Delirium', 'Phosphorus', 2],
  ['Mind > Delirium', 'Aconite', 2], ['Mind > Delirium', 'Arsenicum album', 2],
  ['Mind > Forgetfulness', 'Lycopodium', 2], ['Mind > Forgetfulness', 'Natrum mur', 2],
  ['Mind > Forgetfulness', 'Silicea', 1], ['Mind > Forgetfulness', 'Phosphorus', 1],
  ['Mind > Forgetfulness', 'Zincum met', 2], ['Mind > Forgetfulness', 'Phosphoric acid', 3],
  ['Mind > Forgetfulness', 'Baryta carb', 2],
  ['Mind > Ailments from anger', 'Chamomilla', 3], ['Mind > Ailments from anger', 'Nux vomica', 3],
  ['Mind > Ailments from anger', 'Staphysagria', 3], ['Mind > Ailments from anger', 'Bryonia', 2],
  ['Mind > Ailments from anger', 'Colocynthis', 2],
  ['Mind > Consolation amel.', 'Pulsatilla', 3], ['Mind > Consolation amel.', 'Ignatia', 2],
  ['Mind > Consolation amel.', 'Phosphorus', 2], ['Mind > Consolation amel.', 'Causticum', 1],
  ['Mind > Loquacity', 'Lachesis', 3], ['Mind > Loquacity', 'Hyoscyamus', 3],
  ['Mind > Loquacity', 'Stramonium', 2], ['Mind > Loquacity', 'Veratrum album', 2],
  ['Mind > Suspicion', 'Hyoscyamus', 3], ['Mind > Suspicion', 'Lachesis', 2],
  ['Mind > Suspicion', 'Nux vomica', 2], ['Mind > Suspicion', 'Stramonium', 1],
  ['Mind > Aversion to company', 'Natrum mur', 3], ['Mind > Aversion to company', 'Nux vomica', 2],
  ['Mind > Aversion to company', 'Silicea', 2], ['Mind > Aversion to company', 'Phosphoric acid', 1],
  ['Mind > Desire for company', 'Phosphorus', 3], ['Mind > Desire for company', 'Pulsatilla', 3],
  ['Mind > Desire for company', 'Arsenicum album', 2], ['Mind > Desire for company', 'Stramonium', 2],

  // HEAD
  ['Head > Pain, throbbing', 'Belladonna', 3], ['Head > Pain, throbbing', 'Spigelia', 2],
  ['Head > Pain, throbbing', 'Ferrum phos', 2], ['Head > Pain, throbbing', 'Bryonia', 2],
  ['Head > Pain from light', 'Belladonna', 3], ['Head > Pain from light', 'Bryonia', 2],
  ['Head > Pain from light', 'Pulsatilla', 2], ['Head > Pain from light', 'Natrum mur', 2],
  ['Head > Pain from light', 'Silicea', 1],
  ['Head > Pain, better cold application', 'Belladonna', 3], ['Head > Pain, better cold application', 'Apis mellifica', 2],
  ['Head > Pain, better cold application', 'Bryonia', 2], ['Head > Pain, better cold application', 'Pulsatilla', 2],
  ['Head > Vertigo', 'Gelsemium', 3], ['Head > Vertigo', 'Bryonia', 2],
  ['Head > Vertigo', 'Pulsatilla', 2], ['Head > Vertigo', 'Phosphorus', 2],
  ['Head > Vertigo', 'Silicea', 1], ['Head > Vertigo', 'China', 2],
  ['Head > Pain, stitching', 'Spigelia', 3], ['Head > Pain, stitching', 'Nitric acid', 2],
  ['Head > Pain, stitching', 'Kali bich', 2], ['Head > Pain, stitching', 'Belladonna', 1],
  ['Head > Pain, better warmth', 'Silicea', 2], ['Head > Pain, better warmth', 'Calcarea carb', 2],
  ['Head > Pain, better warmth', 'Natrum mur', 1], ['Head > Pain, better warmth', 'Phosphorus', 1],
  ['Head > Headache, one-sided left', 'Spigelia', 3], ['Head > Headache, one-sided left', 'Lachesis', 3],
  ['Head > Headache, one-sided left', 'Natrum mur', 2], ['Head > Headache, one-sided left', 'Belladonna', 2],
  ['Head > Headache, one-sided right', 'Belladonna', 3], ['Head > Headache, one-sided right', 'Lycopodium', 2],
  ['Head > Headache, one-sided right', 'Bryonia', 2], ['Head > Headache, one-sided right', 'Silicea', 2],
  ['Head > Headache from sun or heat', 'Natrum mur', 3], ['Head > Headache from sun or heat', 'Belladonna', 3],
  ['Head > Headache from sun or heat', 'Lachesis', 2], ['Head > Headache from sun or heat', 'Bryonia', 1],

  // EYE
  ['Eye > Inflammation, redness', 'Apis mellifica', 3], ['Eye > Inflammation, redness', 'Belladonna', 3],
  ['Eye > Inflammation, redness', 'Euphrasia', 2], ['Eye > Inflammation, redness', 'Pulsatilla', 2],
  ['Eye > Inflammation, redness', 'Merc sol', 2], ['Eye > Inflammation, redness', 'Aconite', 2],
  ['Eye > Lachrymation', 'Euphrasia', 3], ['Eye > Lachrymation', 'Allium cepa', 2],
  ['Eye > Lachrymation', 'Pulsatilla', 2], ['Eye > Lachrymation', 'Natrum mur', 2],
  ['Eye > Photophobia', 'Belladonna', 3], ['Eye > Photophobia', 'Euphrasia', 3],
  ['Eye > Photophobia', 'Natrum mur', 2], ['Eye > Photophobia', 'Pulsatilla', 2],
  ['Eye > Photophobia', 'Bryonia', 1],
  ['Eye > Eyes, burning', 'Arsenicum album', 3], ['Eye > Eyes, burning', 'Euphrasia', 2],
  ['Eye > Eyes, burning', 'Sulphur', 2], ['Eye > Eyes, burning', 'Phosphorus', 2],

  // EAR
  ['Ear > Earache', 'Belladonna', 3], ['Ear > Earache', 'Chamomilla', 3],
  ['Ear > Earache', 'Merc sol', 2], ['Ear > Earache', 'Hepar sulph', 2],
  ['Ear > Earache', 'Pulsatilla', 2],
  ['Ear > Ear, discharge', 'Merc sol', 3], ['Ear > Ear, discharge', 'Hepar sulph', 3],
  ['Ear > Ear, discharge', 'Silicea', 3], ['Ear > Ear, discharge', 'Pulsatilla', 2],
  ['Ear > Noises, ringing', 'China', 3], ['Ear > Noises, ringing', 'Silicea', 2],
  ['Ear > Noises, ringing', 'Lycopodium', 2], ['Ear > Noises, ringing', 'Natrum mur', 2],
  ['Ear > Noises, ringing', 'Kali phos', 2],

  // NOSE
  ['Nose > Coryza, bland discharge', 'Allium cepa', 3], ['Nose > Coryza, bland discharge', 'Euphrasia', 3],
  ['Nose > Coryza, bland discharge', 'Pulsatilla', 2], ['Nose > Coryza, bland discharge', 'Natrum mur', 2],
  ['Nose > Coryza, acrid discharge', 'Allium cepa', 3], ['Nose > Coryza, acrid discharge', 'Arsenicum album', 2],
  ['Nose > Coryza, acrid discharge', 'Merc sol', 2], ['Nose > Coryza, acrid discharge', 'Euphrasia', 1],
  ['Nose > Discharge, thick stringy', 'Kali bich', 3], ['Nose > Discharge, thick stringy', 'Pulsatilla', 2],
  ['Nose > Discharge, thick stringy', 'Hydrastis', 2],
  ['Nose > Sneezing, frequent', 'Allium cepa', 3], ['Nose > Sneezing, frequent', 'Arsenicum album', 3],
  ['Nose > Sneezing, frequent', 'Sabadilla', 3], ['Nose > Sneezing, frequent', 'Euphrasia', 2],
  ['Nose > Nosebleed', 'Phosphorus', 3], ['Nose > Nosebleed', 'Hamamelis', 3],
  ['Nose > Nosebleed', 'Millefolium', 3], ['Nose > Nosebleed', 'Ferrum phos', 2],
  ['Nose > Nosebleed', 'Ipecac', 2], ['Nose > Nosebleed', 'Bryonia', 1],
  ['Nose > Smell, loss of', 'Pulsatilla', 2], ['Nose > Smell, loss of', 'Natrum mur', 2],
  ['Nose > Smell, loss of', 'Phosphorus', 2], ['Nose > Smell, loss of', 'Kali bich', 1],

  // MOUTH
  ['Mouth > Tongue, coated white', 'Antimonium crud', 3], ['Mouth > Tongue, coated white', 'Bryonia', 3],
  ['Mouth > Tongue, coated white', 'Nux vomica', 2], ['Mouth > Tongue, coated white', 'Pulsatilla', 2],
  ['Mouth > Tongue, coated white', 'Merc sol', 2],
  ['Mouth > Tongue, dry', 'Bryonia', 3], ['Mouth > Tongue, dry', 'Arsenicum album', 2],
  ['Mouth > Tongue, dry', 'Natrum mur', 2], ['Mouth > Tongue, dry', 'Phosphorus', 2],
  ['Mouth > Taste, bitter', 'Pulsatilla', 3], ['Mouth > Taste, bitter', 'Nux vomica', 3],
  ['Mouth > Taste, bitter', 'Bryonia', 2], ['Mouth > Taste, bitter', 'Merc sol', 2],
  ['Mouth > Lips, cracked', 'Natrum mur', 3], ['Mouth > Lips, cracked', 'Arsenicum album', 2],
  ['Mouth > Lips, cracked', 'Sulphur', 2], ['Mouth > Lips, cracked', 'Graphites', 2],
  ['Mouth > Mouth, ulcers', 'Merc sol', 3], ['Mouth > Mouth, ulcers', 'Borax', 3],
  ['Mouth > Mouth, ulcers', 'Nitric acid', 3], ['Mouth > Mouth, ulcers', 'Sulphur', 2],
  ['Mouth > Mouth, ulcers', 'Arsenicum album', 2],

  // TEETH
  ['Teeth > Toothache, better cold', 'Pulsatilla', 3], ['Teeth > Toothache, better cold', 'Silicea', 2],
  ['Teeth > Toothache, better cold', 'Staphysagria', 2],
  ['Teeth > Toothache, worse warmth', 'Pulsatilla', 3], ['Teeth > Toothache, worse warmth', 'Silicea', 2],
  ['Teeth > Toothache, worse warmth', 'Merc sol', 2],
  ['Teeth > Teeth, grinding', 'Cuprum met', 2], ['Teeth > Teeth, grinding', 'Belladonna', 2],
  ['Teeth > Teeth, grinding', 'Hyoscyamus', 2], ['Teeth > Teeth, grinding', 'Chamomilla', 1],

  // FACE
  ['Face > Face red, hot', 'Belladonna', 3], ['Face > Face red, hot', 'Aconite', 3],
  ['Face > Face red, hot', 'Chamomilla', 2], ['Face > Face red, hot', 'Ferrum phos', 2],
  ['Face > Face red, hot', 'Gelsemium', 1],

  // THROAT
  ['Throat > Sore throat, better cold drinks', 'Belladonna', 3], ['Throat > Sore throat, better cold drinks', 'Apis mellifica', 3],
  ['Throat > Sore throat, better cold drinks', 'Lachesis', 2], ['Throat > Sore throat, better cold drinks', 'Merc sol', 2],
  ['Throat > Sore throat, better cold drinks', 'Phosphorus', 2],
  ['Throat > Pain, stinging', 'Apis mellifica', 3], ['Throat > Pain, stinging', 'Belladonna', 2],
  ['Throat > Pain, stinging', 'Merc sol', 2], ['Throat > Pain, stinging', 'Hepar sulph', 2],
  ['Throat > Pain, stinging', 'Arsenicum album', 2],
  ['Throat > Throat, dry', 'Bryonia', 3], ['Throat > Throat, dry', 'Arsenicum album', 2],
  ['Throat > Throat, dry', 'Phosphorus', 2], ['Throat > Throat, dry', 'Natrum mur', 2],
  ['Throat > Swallowing, painful', 'Belladonna', 3], ['Throat > Swallowing, painful', 'Merc sol', 3],
  ['Throat > Swallowing, painful', 'Lachesis', 3], ['Throat > Swallowing, painful', 'Hepar sulph', 2],
  ['Throat > Swallowing, painful', 'Arsenicum album', 2],

  // STOMACH
  ['Stomach > Nausea', 'Ipecac', 3], ['Stomach > Nausea', 'Nux vomica', 3],
  ['Stomach > Nausea', 'Arsenicum album', 2], ['Stomach > Nausea', 'Pulsatilla', 2],
  ['Stomach > Nausea', 'Phosphorus', 2],
  ['Stomach > Thirst, extreme', 'Arsenicum album', 3], ['Stomach > Thirst, extreme', 'Bryonia', 3],
  ['Stomach > Thirst, extreme', 'Phosphorus', 3], ['Stomach > Thirst, extreme', 'Natrum mur', 2],
  ['Stomach > Thirst, extreme', 'Sulphur', 2], ['Stomach > Thirst, extreme', 'China', 2],
  ['Stomach > Thirstless', 'Pulsatilla', 3], ['Stomach > Thirstless', 'Apis mellifica', 2],
  ['Stomach > Thirstless', 'Gelsemium', 2], ['Stomach > Thirstless', 'China', 1],
  ['Stomach > Vomiting', 'Ipecac', 3], ['Stomach > Vomiting', 'Veratrum album', 3],
  ['Stomach > Vomiting', 'Arsenicum album', 3], ['Stomach > Vomiting', 'Nux vomica', 2],
  ['Stomach > Vomiting', 'Phosphorus', 2],
  ['Stomach > Appetite loss', 'China', 2], ['Stomach > Appetite loss', 'Pulsatilla', 3],
  ['Stomach > Appetite loss', 'Lycopodium', 2], ['Stomach > Appetite loss', 'Arsenicum album', 1],
  ['Stomach > Craving, salt', 'Natrum mur', 3], ['Stomach > Craving, salt', 'Phosphorus', 2],
  ['Stomach > Craving, salt', 'Sulphur', 1],
  ['Stomach > Craving, sweets', 'Argentum nitricum', 3], ['Stomach > Craving, sweets', 'Sulphur', 3],
  ['Stomach > Craving, sweets', 'Lycopodium', 2], ['Stomach > Craving, sweets', 'Phosphorus', 2],
  ['Stomach > Aversion to food', 'Pulsatilla', 3], ['Stomach > Aversion to food', 'China', 3],
  ['Stomach > Aversion to food', 'Arsenicum album', 2], ['Stomach > Aversion to food', 'Lycopodium', 2],
  ['Stomach > Hiccough', 'Ipecac', 2], ['Stomach > Hiccough', 'Nux vomica', 2],
  ['Stomach > Hiccough', 'Cuprum met', 2], ['Stomach > Hiccough', 'Phosphorus', 1],

  // ABDOMEN
  ['Abdomen > Flatulence, bloating', 'Carbo veg', 3], ['Abdomen > Flatulence, bloating', 'Lycopodium', 3],
  ['Abdomen > Flatulence, bloating', 'China', 3], ['Abdomen > Flatulence, bloating', 'Argentum nitricum', 2],
  ['Abdomen > Flatulence, bloating', 'Nux vomica', 2],
  ['Abdomen > Pain, colic', 'Colocynthis', 3], ['Abdomen > Pain, colic', 'Magnesia phos', 3],
  ['Abdomen > Pain, colic', 'Chamomilla', 3], ['Abdomen > Pain, colic', 'Cuprum met', 2],
  ['Abdomen > Pain, colic', 'Veratrum album', 2],
  ['Abdomen > Pain, better bending double', 'Colocynthis', 3], ['Abdomen > Pain, better bending double', 'Magnesia phos', 3],
  ['Abdomen > Pain, better bending double', 'Chamomilla', 2], ['Abdomen > Pain, better bending double', 'Cuprum met', 2],

  // RECTUM
  ['Rectum > Diarrhoea', 'Arsenicum album', 3], ['Rectum > Diarrhoea', 'Veratrum album', 3],
  ['Rectum > Diarrhoea', 'Sulphur', 3], ['Rectum > Diarrhoea', 'Chamomilla', 2],
  ['Rectum > Diarrhoea', 'Pulsatilla', 2],
  ['Rectum > Constipation', 'Nux vomica', 3], ['Rectum > Constipation', 'Bryonia', 3],
  ['Rectum > Constipation', 'Silicea', 2], ['Rectum > Constipation', 'Lycopodium', 2],
  ['Rectum > Constipation', 'Graphites', 2], ['Rectum > Constipation', 'Alumina', 3],
  ['Rectum > Constipation', 'Plumbum met', 3], ['Rectum > Constipation', 'Opium', 2],
  ['Rectum > Diarrhoea from fruit', 'China', 3], ['Rectum > Diarrhoea from fruit', 'Arsenicum album', 2],
  ['Rectum > Diarrhoea from fruit', 'Sulphur', 2], ['Rectum > Diarrhoea from fruit', 'Pulsatilla', 1],
  ['Rectum > Stool, ineffectual urging', 'Nux vomica', 3], ['Rectum > Stool, ineffectual urging', 'Lycopodium', 2],
  ['Rectum > Stool, ineffectual urging', 'Silicea', 2], ['Rectum > Stool, ineffectual urging', 'Alumina', 2],
  ['Rectum > Stool, hard lumps', 'Bryonia', 3], ['Rectum > Stool, hard lumps', 'Alumina', 3],
  ['Rectum > Stool, hard lumps', 'Plumbum met', 3], ['Rectum > Stool, hard lumps', 'Silicea', 2],
  ['Rectum > Stool, hard lumps', 'Natrum mur', 2],
  ['Rectum > Bleeding piles', 'Hamamelis', 3], ['Rectum > Bleeding piles', 'Millefolium', 3],
  ['Rectum > Bleeding piles', 'Sulphur', 3], ['Rectum > Bleeding piles', 'Nitric acid', 2],
  ['Rectum > Bleeding piles', 'Arsenicum album', 2],

  // URINE
  ['Urine > Urine, burning', 'Cantharis', 3], ['Urine > Urine, burning', 'Arsenicum album', 3],
  ['Urine > Urine, burning', 'Merc sol', 2], ['Urine > Urine, burning', 'Sulphur', 2],
  ['Urine > Urine, burning', 'Apis mellifica', 2],
  ['Urine > Urine, frequent urging', 'Cantharis', 3], ['Urine > Urine, frequent urging', 'Pulsatilla', 2],
  ['Urine > Urine, frequent urging', 'Nux vomica', 2], ['Urine > Urine, frequent urging', 'Causticum', 2],
  ['Urine > Urine, scanty', 'Apis mellifica', 3], ['Urine > Urine, scanty', 'Cantharis', 2],
  ['Urine > Urine, scanty', 'Arsenicum album', 2],

  // RESPIRATION
  ['Respiration > Breathing, difficult', 'Arsenicum album', 3], ['Respiration > Breathing, difficult', 'Antimonium tart', 3],
  ['Respiration > Breathing, difficult', 'Carbo veg', 3], ['Respiration > Breathing, difficult', 'Phosphorus', 3],
  ['Respiration > Breathing, difficult', 'Lachesis', 2], ['Respiration > Breathing, difficult', 'Ipecac', 2],
  ['Respiration > Breathing, better open air', 'Pulsatilla', 3], ['Respiration > Breathing, better open air', 'Carbo veg', 3],
  ['Respiration > Breathing, better open air', 'Lachesis', 2], ['Respiration > Breathing, better open air', 'Phosphorus', 2],
  ['Respiration > Breath, short', 'Arsenicum album', 3], ['Respiration > Breath, short', 'Phosphorus', 3],
  ['Respiration > Breath, short', 'Carbo veg', 2], ['Respiration > Breath, short', 'Antimonium tart', 2],
  ['Respiration > Breath, short', 'Ipecac', 2],

  // COUGH
  ['Cough > Cough, dry', 'Bryonia', 3], ['Cough > Cough, dry', 'Aconite', 3],
  ['Cough > Cough, dry', 'Phosphorus', 3], ['Cough > Cough, dry', 'Drosera', 2],
  ['Cough > Cough, dry', 'Belladonna', 2], ['Cough > Cough, dry', 'Causticum', 2],
  ['Cough > Cough, loose rattling', 'Antimonium tart', 3], ['Cough > Cough, loose rattling', 'Ipecac', 2],
  ['Cough > Cough, loose rattling', 'Hepar sulph', 2], ['Cough > Cough, loose rattling', 'Pulsatilla', 2],
  ['Cough > Cough, worse at night', 'Drosera', 3], ['Cough > Cough, worse at night', 'Bryonia', 2],
  ['Cough > Cough, worse at night', 'Pulsatilla', 1], ['Cough > Cough, worse at night', 'Hepar sulph', 2],
  ['Cough > Cough, croupy barking', 'Aconite', 3], ['Cough > Cough, croupy barking', 'Hepar sulph', 3],
  ['Cough > Cough, croupy barking', 'Spongia tosta', 3], ['Cough > Cough, croupy barking', 'Drosera', 2],
  ['Cough > Cough, croupy barking', 'Belladonna', 2],
  ['Cough > Cough, better warmth', 'Spongia tosta', 2], ['Cough > Cough, better warmth', 'Causticum', 2],
  ['Cough > Cough, better warmth', 'Hepar sulph', 1], ['Cough > Cough, better warmth', 'Phosphorus', 1],
  ['Cough > Cough, with expectoration', 'Antimonium tart', 3], ['Cough > Cough, with expectoration', 'Pulsatilla', 3],
  ['Cough > Cough, with expectoration', 'Kali bich', 3], ['Cough > Cough, with expectoration', 'Ipecac', 2],
  ['Cough > Cough, with expectoration', 'Hepar sulph', 2],

  // CHEST
  ['Chest > Oppression of chest', 'Phosphorus', 3], ['Chest > Oppression of chest', 'Arsenicum album', 3],
  ['Chest > Oppression of chest', 'Lachesis', 2], ['Chest > Oppression of chest', 'Sulphur', 2],
  ['Chest > Oppression of chest', 'Carbo veg', 2],
  ['Chest > Palpitation', 'Phosphorus', 3], ['Chest > Palpitation', 'Lachesis', 3],
  ['Chest > Palpitation', 'Spigelia', 3], ['Chest > Palpitation', 'Natrum mur', 2],
  ['Chest > Palpitation', 'Kali phos', 2], ['Chest > Palpitation', 'Arsenicum album', 2],

  // BACK
  ['Back > Backache, better from motion', 'Rhus tox', 3], ['Back > Backache, better from motion', 'Bryonia', 1],
  ['Back > Backache, worse sitting', 'Sulphur', 2], ['Back > Backache, worse sitting', 'Natrum mur', 2],
  ['Back > Backache, worse sitting', 'Calcarea carb', 2], ['Back > Backache, worse sitting', 'Nux vomica', 2],

  // EXTREMITIES
  ['Extremities > Joint pain, better continued motion', 'Rhus tox', 3], ['Extremities > Joint pain, better continued motion', 'Bryonia', 1],
  ['Extremities > Cramps, calves', 'Colocynthis', 3], ['Extremities > Cramps, calves', 'Magnesia phos', 3],
  ['Extremities > Cramps, calves', 'Cuprum met', 2], ['Extremities > Cramps, calves', 'Nux vomica', 2],
  ['Extremities > Hands, cold', 'Arsenicum album', 2], ['Extremities > Hands, cold', 'Carbo veg', 2],
  ['Extremities > Hands, cold', 'Silicea', 2], ['Extremities > Hands, cold', 'Secale cor', 2],
  ['Extremities > Feet, cold', 'Pulsatilla', 2], ['Extremities > Feet, cold', 'Silicea', 2],
  ['Extremities > Feet, cold', 'Carbo veg', 2], ['Extremities > Feet, cold', 'Sulphur', 1],
  ['Extremities > Trembling, hands', 'Gelsemium', 3], ['Extremities > Trembling, hands', 'Cuprum met', 3],
  ['Extremities > Trembling, hands', 'Kali phos', 2], ['Extremities > Trembling, hands', 'Arsenicum album', 2],

  // SLEEP
  ['Sleep > Sleeplessness', 'Coffea cruda', 3], ['Sleep > Sleeplessness', 'Nux vomica', 3],
  ['Sleep > Sleeplessness', 'Arsenicum album', 2], ['Sleep > Sleeplessness', 'Ignatia', 2],
  ['Sleep > Sleeplessness', 'Pulsatilla', 1],
  ['Sleep > Dreams, anxious', 'Arsenicum album', 2], ['Sleep > Dreams, anxious', 'Natrum mur', 2],
  ['Sleep > Dreams, anxious', 'Silicea', 1],
  ['Sleep > Sleepiness, daytime', 'Gelsemium', 3], ['Sleep > Sleepiness, daytime', 'Phosphoric acid', 3],
  ['Sleep > Sleepiness, daytime', 'Opium', 3], ['Sleep > Sleepiness, daytime', 'Antimonium tart', 2],
  ['Sleep > Waking, early', 'Natrum mur', 3], ['Sleep > Waking, early', 'Kali phos', 2],
  ['Sleep > Waking, early', 'Sulphur', 2], ['Sleep > Waking, early', 'Phosphoric acid', 2],

  // FEVER
  ['Fever > Fever with thirst', 'Aconite', 3], ['Fever > Fever with thirst', 'Bryonia', 3],
  ['Fever > Fever with thirst', 'Arsenicum album', 2], ['Fever > Fever with thirst', 'Natrum mur', 2],
  ['Fever > Chill, shivering', 'Nux vomica', 3], ['Fever > Chill, shivering', 'Silicea', 3],
  ['Fever > Chill, shivering', 'Natrum mur', 2], ['Fever > Chill, shivering', 'Pulsatilla', 2],
  ['Fever > Heat, burning', 'Arsenicum album', 3], ['Fever > Heat, burning', 'Phosphorus', 3],
  ['Fever > Heat, burning', 'Sulphur', 3], ['Fever > Heat, burning', 'Belladonna', 2],
  ['Fever > Sweat, profuse', 'Merc sol', 3], ['Fever > Sweat, profuse', 'China', 3],
  ['Fever > Sweat, profuse', 'Phosphorus', 3], ['Fever > Sweat, profuse', 'Calcarea carb', 2],
  ['Fever > Sweat, profuse', 'Silicea', 2],
  ['Fever > Sweat, night', 'China', 3], ['Fever > Sweat, night', 'Silicea', 3],
  ['Fever > Sweat, night', 'Phosphorus', 3], ['Fever > Sweat, night', 'Calcarea carb', 2],
  ['Fever > Sweat, night', 'Merc sol', 2],

  // SKIN
  ['Skin > Urticaria, hives', 'Apis mellifica', 3], ['Skin > Urticaria, hives', 'Natrum mur', 2],
  ['Skin > Urticaria, hives', 'Sulphur', 2], ['Skin > Urticaria, hives', 'Rhus tox', 2],
  ['Skin > Boils, abscess', 'Hepar sulph', 3], ['Skin > Boils, abscess', 'Silicea', 3],
  ['Skin > Boils, abscess', 'Belladonna', 2], ['Skin > Boils, abscess', 'Merc sol', 2],
  ['Skin > Boils, abscess', 'Calendula', 2],
  ['Skin > Eruptions, itching', 'Sulphur', 3], ['Skin > Eruptions, itching', 'Rhus tox', 3],
  ['Skin > Eruptions, itching', 'Arsenicum album', 2], ['Skin > Eruptions, itching', 'Graphites', 2],
  ['Skin > Eruptions, itching', 'Merc sol', 2],
  ['Skin > Warts', 'Thuja', 3], ['Skin > Warts', 'Dulcamara', 1], ['Skin > Warts', 'Natrum mur', 1],
  ['Skin > Warts', 'Nitric acid', 2], ['Skin > Warts', 'Causticum', 2],
  ['Skin > Skin, dry', 'Arsenicum album', 3], ['Skin > Skin, dry', 'Sulphur', 3],
  ['Skin > Skin, dry', 'Graphites', 3], ['Skin > Skin, dry', 'Natrum mur', 2],
  ['Skin > Skin, dry', 'Alumina', 2],
  ['Skin > Bruises easily', 'Arnica montana', 3], ['Skin > Bruises easily', 'Hamamelis', 3],
  ['Skin > Bruises easily', 'Phosphorus', 3], ['Skin > Bruises easily', 'Lachesis', 2],
  ['Skin > Bruises easily', 'China', 2],

  // FEMALE
  ['Female > Menses, too early', 'Natrum mur', 3], ['Female > Menses, too early', 'Sepia', 2],
  ['Female > Menses, too early', 'Calcarea carb', 2], ['Female > Menses, too early', 'Phosphorus', 2],
  ['Female > Menses, too late', 'Pulsatilla', 3], ['Female > Menses, too late', 'Lycopodium', 2],
  ['Female > Menses, too late', 'Graphites', 2], ['Female > Menses, too late', 'Sepia', 2],
  ['Female > Menses, profuse', 'Sabina', 3], ['Female > Menses, profuse', 'Millefolium', 3],
  ['Female > Menses, profuse', 'Secale cor', 2], ['Female > Menses, profuse', 'Phosphorus', 2],
  ['Female > Menses, profuse', 'Hamamelis', 2],

  // GENERALITIES
  ['Generalities > Injury, bruises', 'Arnica montana', 3], ['Generalities > Injury, bruises', 'Ledum', 3],
  ['Generalities > Injury, bruises', 'Hypericum', 2], ['Generalities > Injury, bruises', 'Ruta graveolens', 2],
  ['Generalities > Injury, bruises', 'Bellis perennis', 3],
  ['Generalities > Wounds, punctured', 'Ledum', 3], ['Generalities > Wounds, punctured', 'Hypericum', 3],
  ['Generalities > Wounds, punctured', 'Silicea', 2], ['Generalities > Wounds, punctured', 'Calendula', 2],
  ['Generalities > Weakness, prostration', 'Arsenicum album', 3], ['Generalities > Weakness, prostration', 'Phosphorus', 3],
  ['Generalities > Weakness, prostration', 'Gelsemium', 3], ['Generalities > Weakness, prostration', 'China', 3],
  ['Generalities > Weakness, prostration', 'Veratrum album', 2], ['Generalities > Weakness, prostration', 'Sulphur', 1],
  ['Generalities > Weakness, prostration', 'Phosphoric acid', 3], ['Generalities > Weakness, prostration', 'Ferrum met', 3],
  ['Generalities > Better from cold', 'Apis mellifica', 3], ['Generalities > Better from cold', 'Belladonna', 2],
  ['Generalities > Better from cold', 'Sulphur', 2], ['Generalities > Better from cold', 'Pulsatilla', 2],
  ['Generalities > Better from cold', 'Argentum nitricum', 1], ['Generalities > Better from cold', 'Ledum', 2],
  ['Generalities > Worse from cold, damp', 'Rhus tox', 3], ['Generalities > Worse from cold, damp', 'Dulcamara', 3],
  ['Generalities > Worse from cold, damp', 'Calcarea carb', 2], ['Generalities > Worse from cold, damp', 'Silicea', 2],
  ['Generalities > Worse from cold, damp', 'Hepar sulph', 2], ['Generalities > Worse from cold, damp', 'Natrum sulph', 3],
  ['Generalities > Worse from heat', 'Apis mellifica', 3], ['Generalities > Worse from heat', 'Pulsatilla', 3],
  ['Generalities > Worse from heat', 'Sulphur', 3], ['Generalities > Worse from heat', 'Belladonna', 2],
  ['Generalities > Worse from heat', 'Argentum nitricum', 1], ['Generalities > Worse from heat', 'Lachesis', 2],
  ['Generalities > Better from motion', 'Rhus tox', 3], ['Generalities > Better from motion', 'Sepia', 2],
  ['Generalities > Better from motion', 'Lycopodium', 1], ['Generalities > Better from motion', 'Pulsatilla', 1],
  ['Generalities > Worse from motion', 'Bryonia', 3], ['Generalities > Worse from motion', 'Belladonna', 2],
  ['Generalities > Worse from motion', 'Colocynthis', 1], ['Generalities > Worse from motion', 'Kali bich', 1],
  ['Generalities > Better from warmth', 'Rhus tox', 2], ['Generalities > Better from warmth', 'Silicea', 2],
  ['Generalities > Better from warmth', 'Calcarea carb', 2], ['Generalities > Better from warmth', 'Magnesia phos', 3],
  ['Generalities > Better from warmth', 'Hepar sulph', 2],
  ['Generalities > Worse evening or night', 'Arsenicum album', 3], ['Generalities > Worse evening or night', 'Rhus tox', 2],
  ['Generalities > Worse evening or night', 'Pulsatilla', 2], ['Generalities > Worse evening or night', 'Drosera', 2],
  ['Generalities > Worse evening or night', 'Merc sol', 2],
  ['Generalities > Worse morning', 'Nux vomica', 3], ['Generalities > Worse morning', 'Natrum mur', 3],
  ['Generalities > Worse morning', 'Sulphur', 2], ['Generalities > Worse morning', 'Bryonia', 2],

  // নতুন রুব্রিকের লিংক
  ['Mind > Sadness, melancholy', 'Aurum met', 3], ['Mind > Sadness, melancholy', 'Natrum mur', 3],
  ['Mind > Sadness, melancholy', 'Pulsatilla', 3], ['Mind > Sadness, melancholy', 'Ignatia', 3],
  ['Mind > Sadness, melancholy', 'Cimicifuga', 2], ['Mind > Sadness, melancholy', 'Sepia', 2],
  ['Mind > Sadness, melancholy', 'Psorinum', 3], ['Mind > Sadness, melancholy', 'Phosphoric acid', 2],
  ['Mind > Fear, being alone', 'Phosphorus', 3], ['Mind > Fear, being alone', 'Arsenicum album', 3],
  ['Mind > Fear, being alone', 'Pulsatilla', 3], ['Mind > Fear, being alone', 'Aconite', 2],
  ['Mind > Fear, being alone', 'Lycopodium', 2], ['Mind > Fear, being alone', 'Stramonium', 2],
  ['Head > Headache, better sleep', 'Sanguinaria', 3], ['Head > Headache, better sleep', 'Natrum mur', 2],
  ['Head > Headache, better sleep', 'Gelsemium', 2], ['Head > Headache, better sleep', 'Silicea', 2],
  ['Nose > Discharge, yellow', 'Kali sulph', 3], ['Nose > Discharge, yellow', 'Kali bich', 2],
  ['Nose > Discharge, yellow', 'Pulsatilla', 3], ['Nose > Discharge, yellow', 'Hydrastis', 2],
  ['Nose > Discharge, yellow', 'Merc sol', 2], ['Nose > Discharge, yellow', 'Sulphur', 2],
  ['Stomach > Eructations, sour', 'Natrum phos', 3], ['Stomach > Eructations, sour', 'China', 2],
  ['Stomach > Eructations, sour', 'Lycopodium', 2], ['Stomach > Eructations, sour', 'Carbo veg', 2],
  ['Stomach > Eructations, sour', 'Antimonium crud', 2], ['Stomach > Eructations, sour', 'Calcarea carb', 2],
  ['Stomach > Stomach, empty feeling', 'Anacardium', 3], ['Stomach > Stomach, empty feeling', 'Ignatia', 2],
  ['Stomach > Stomach, empty feeling', 'Phosphorus', 3], ['Stomach > Stomach, empty feeling', 'Sulphur', 3],
  ['Stomach > Stomach, empty feeling', 'Hydrastis', 2], ['Stomach > Stomach, empty feeling', 'Sepia', 2],
  ['Stomach > Nausea not relieved by vomiting', 'Ipecac', 3], ['Stomach > Nausea not relieved by vomiting', 'Antimonium tart', 2],
  ['Stomach > Nausea not relieved by vomiting', 'Arsenicum album', 2], ['Stomach > Nausea not relieved by vomiting', 'Tabacum', 2],
  ['Stomach > Nausea not relieved by vomiting', 'Colocynthis', 1], ['Stomach > Nausea not relieved by vomiting', 'Nux vomica', 2],
  ['Abdomen > Pain, better stretching', 'Dioscorea', 3], ['Abdomen > Pain, better stretching', 'Lycopodium', 1],
  ['Abdomen > Pain, better stretching', 'Cina', 1], ['Abdomen > Pain, better stretching', 'Mag carb', 1],
  ['Abdomen > Liver, sore and enlarged', 'Chelidonium', 3], ['Abdomen > Liver, sore and enlarged', 'Aloe', 2],
  ['Abdomen > Liver, sore and enlarged', 'Lycopodium', 3], ['Abdomen > Liver, sore and enlarged', 'Natrum sulph', 2],
  ['Abdomen > Liver, sore and enlarged', 'Podophyllum', 2], ['Abdomen > Liver, sore and enlarged', 'Digitalis', 2],
  ['Abdomen > Liver, sore and enlarged', 'Baptisia', 2], ['Abdomen > Liver, sore and enlarged', 'Merc sol', 1],
  ['Rectum > Diarrhoea, morning', 'Aloe', 3], ['Rectum > Diarrhoea, morning', 'Podophyllum', 3],
  ['Rectum > Diarrhoea, morning', 'Sulphur', 3], ['Rectum > Diarrhoea, morning', 'Nux vomica', 2],
  ['Rectum > Diarrhoea, morning', 'Natrum sulph', 2], ['Rectum > Diarrhoea, morning', 'Kali bich', 1],
  ['Rectum > Worms', 'Cina', 3], ['Rectum > Worms', 'Natrum phos', 2],
  ['Rectum > Worms', 'Sabadilla', 2], ['Rectum > Worms', 'Calcarea carb', 2],
  ['Rectum > Worms', 'Sulphur', 1], ['Rectum > Worms', 'Spigelia', 2],
  ['Rectum > Piles, burning', 'Aesculus', 3], ['Rectum > Piles, burning', 'Aloe', 3],
  ['Rectum > Piles, burning', 'Nux vomica', 3], ['Rectum > Piles, burning', 'Sulphur', 2],
  ['Rectum > Piles, burning', 'Arsenicum album', 2], ['Rectum > Piles, burning', 'Hamamelis', 2],
  ['Rectum > Stool, offensive', 'Baptisia', 3], ['Rectum > Stool, offensive', 'Psorinum', 3],
  ['Rectum > Stool, offensive', 'Sulphur', 2], ['Rectum > Stool, offensive', 'Carbo veg', 2],
  ['Rectum > Stool, offensive', 'Podophyllum', 2], ['Rectum > Stool, offensive', 'Merc sol', 2],
  ['Urine > Urine, stone and gravel', 'Sarsaparilla', 3], ['Urine > Urine, stone and gravel', 'Lycopodium', 3],
  ['Urine > Urine, stone and gravel', 'Natrum sulph', 2], ['Urine > Urine, stone and gravel', 'Calcarea carb', 2],
  ['Urine > Urine, involuntary', 'Causticum', 3], ['Urine > Urine, involuntary', 'Gelsemium', 2],
  ['Urine > Urine, involuntary', 'Sepia', 2], ['Urine > Urine, involuntary', 'Squilla', 2],
  ['Urine > Urine, involuntary', 'Pulsatilla', 2], ['Urine > Urine, involuntary', 'Staphysagria', 1],
  ['Throat > Throat, raw scraping', 'Phytolacca', 3], ['Throat > Throat, raw scraping', 'Sanguinaria', 2],
  ['Throat > Throat, raw scraping', 'Causticum', 2], ['Throat > Throat, raw scraping', 'Arsenicum album', 2],
  ['Throat > Throat, raw scraping', 'Arsenicum album', 2], ['Throat > Throat, raw scraping', 'Kali bich', 2],
  ['Cough > Cough, worse cold air', 'Arsenicum album', 3], ['Cough > Cough, worse cold air', 'Belladonna', 2],
  ['Cough > Cough, worse cold air', 'Hepar sulph', 3], ['Cough > Cough, worse cold air', 'Silicea', 2],
  ['Cough > Cough, worse cold air', 'Spongia tosta', 2], ['Cough > Cough, worse cold air', 'Phytolacca', 2],
  ['Cough > Cough, with involuntary urination', 'Squilla', 3], ['Cough > Cough, with involuntary urination', 'Causticum', 3],
  ['Cough > Cough, with involuntary urination', 'Pulsatilla', 2], ['Cough > Cough, with involuntary urination', 'Natrum mur', 1],
  ['Chest > Chest, heart pain', 'Cactus', 3], ['Chest > Chest, heart pain', 'Digitalis', 3],
  ['Chest > Chest, heart pain', 'Spigelia', 3], ['Chest > Chest, heart pain', 'Aurum met', 2],
  ['Chest > Chest, heart pain', 'Lilium tigrinum', 2], ['Chest > Chest, heart pain', 'Arsenicum album', 2],
  ['Chest > Chest, constriction', 'Cactus', 3], ['Chest > Chest, constriction', 'Arsenicum album', 2],
  ['Chest > Chest, constriction', 'Kali carb', 2], ['Chest > Chest, constriction', 'Digitalis', 2],
  ['Chest > Chest, constriction', 'Lachesis', 2], ['Chest > Chest, constriction', 'Lilium tigrinum', 2],
  ['Extremities > Pain, bones', 'Eupatorium perf', 3], ['Extremities > Pain, bones', 'Rhus tox', 2],
  ['Extremities > Pain, bones', 'Phytolacca', 2], ['Extremities > Pain, bones', 'Aurum met', 2],
  ['Extremities > Pain, bones', 'Silicea', 1], ['Extremities > Pain, bones', 'Ruta graveolens', 2],
  ['Extremities > Cramps, better stretching', 'Dioscorea', 3], ['Extremities > Cramps, better stretching', 'Cuprum met', 2],
  ['Extremities > Cramps, better stretching', 'Magnesia phos', 2], ['Extremities > Cramps, better stretching', 'Colocynthis', 2],
  ['Extremities > Cramps, better stretching', 'Sarsaparilla', 1],
  ['Extremities > Pain, shifting', 'Pulsatilla', 3], ['Extremities > Pain, shifting', 'Kali bich', 2],
  ['Extremities > Pain, shifting', 'Rhus tox', 1], ['Extremities > Pain, shifting', 'Dulcamara', 1],
  ['Sleep > Sleeplessness from thoughts', 'Coffea cruda', 3], ['Sleep > Sleeplessness from thoughts', 'Kali phos', 3],
  ['Sleep > Sleeplessness from thoughts', 'Nux vomica', 2], ['Sleep > Sleeplessness from thoughts', 'Arsenicum album', 2],
  ['Sleep > Sleeplessness from thoughts', 'Ignatia', 2], ['Sleep > Sleeplessness from thoughts', 'Ambra grisea', 2],
  ['Sleep > Sleeplessness, children', 'Chamomilla', 3], ['Sleep > Sleeplessness, children', 'Cina', 3],
  ['Sleep > Sleeplessness, children', 'Tarentula', 3], ['Sleep > Sleeplessness, children', 'Kreosote', 2],
  ['Sleep > Sleeplessness, children', 'Stramonium', 2], ['Sleep > Sleeplessness, children', 'Mag carb', 2],
  ['Skin > Eruptions, cracking', 'Petroleum', 3], ['Skin > Eruptions, cracking', 'Graphites', 3],
  ['Skin > Eruptions, cracking', 'Silicea', 2], ['Skin > Eruptions, cracking', 'Natrum mur', 2],
  ['Skin > Eruptions, cracking', 'Sulphur', 2], ['Skin > Eruptions, cracking', 'Rhus tox', 1],
  ['Skin > Ulcers, chronic', 'Fluoric acid', 3], ['Skin > Ulcers, chronic', 'Silicea', 3],
  ['Skin > Ulcers, chronic', 'Calendula', 2], ['Skin > Ulcers, chronic', 'Arsenicum album', 2],
  ['Skin > Ulcers, chronic', 'Pyrogenium', 2], ['Skin > Ulcers, chronic', 'Nitric acid', 2],
  ['Skin > Sweat, offensive', 'Psorinum', 3], ['Skin > Sweat, offensive', 'Silicea', 3],
  ['Skin > Sweat, offensive', 'Merc sol', 3], ['Skin > Sweat, offensive', 'Sulphur', 2],
  ['Skin > Sweat, offensive', 'Tuberculinum', 2], ['Skin > Sweat, offensive', 'Baptisia', 2],
  ['Female > Menses, painful', 'Cimicifuga', 3], ['Female > Menses, painful', 'Magnesia phos', 3],
  ['Female > Menses, painful', 'Colocynthis', 3], ['Female > Menses, painful', 'Nux vomica', 2],
  ['Female > Menses, painful', 'Pulsatilla', 2], ['Female > Menses, painful', 'Sepia', 2],
  ['Female > Leucorrhoea', 'Pulsatilla', 3], ['Female > Leucorrhoea', 'Sepia', 3],
  ['Female > Leucorrhoea', 'Kreosote', 3], ['Female > Leucorrhoea', 'Phytolacca', 2],
  ['Female > Leucorrhoea', 'Kali mur', 2], ['Female > Leucorrhoea', 'Calcarea carb', 2],
  ['Generalities > Food poisoning', 'Arsenicum album', 3], ['Generalities > Food poisoning', 'Nux vomica', 2],
  ['Generalities > Food poisoning', 'Ipecac', 2], ['Generalities > Food poisoning', 'Veratrum album', 2],
  ['Generalities > Food poisoning', 'Baptisia', 2], ['Generalities > Food poisoning', 'Carbo veg', 2],
  ['Generalities > Sepsis, pus formation', 'Pyrogenium', 3], ['Generalities > Sepsis, pus formation', 'Hepar sulph', 3],
  ['Generalities > Sepsis, pus formation', 'Silicea', 3], ['Generalities > Sepsis, pus formation', 'Merc sol', 2],
  ['Generalities > Sepsis, pus formation', 'Baptisia', 2], ['Generalities > Sepsis, pus formation', 'Calendula', 2],
  ['Generalities > Sepsis, pus formation', 'Arsenicum album', 2],
  ['Generalities > Better from pressure', 'Bryonia', 3], ['Generalities > Better from pressure', 'Colocynthis', 3],
  ['Generalities > Better from pressure', 'Magnesia phos', 3], ['Generalities > Better from pressure', 'Arnica montana', 2],
  ['Generalities > Better from pressure', 'Cina', 2], ['Generalities > Better from pressure', 'Chelidonium', 2],
  ['Generalities > Worse from cold wind', 'Belladonna', 2], ['Generalities > Worse from cold wind', 'Hepar sulph', 3],
  ['Generalities > Worse from cold wind', 'Silicea', 3], ['Generalities > Worse from cold wind', 'Aconite', 3],
  ['Generalities > Worse from cold wind', 'Nux vomica', 2], ['Generalities > Worse from cold wind', 'Capsicum', 2],

  // নতুন ওষুধের পুরোনো রুব্রিকের সাথে লিংক
  ['Rectum > Constipation', 'Aesculus', 2], ['Throat > Throat, dry', 'Aesculus', 2],
  ['Back > Backache, worse sitting', 'Aesculus', 2],
  ['Rectum > Diarrhoea', 'Aloe', 3], ['Generalities > Worse morning', 'Aloe', 2],
  ['Sleep > Sleeplessness', 'Ambra grisea', 3], ['Mind > Aversion to company', 'Ambra grisea', 2],
  ['Mind > Forgetfulness', 'Anacardium', 3], ['Mind > Irritability', 'Anacardium', 2],
  ['Stomach > Appetite loss', 'Anacardium', 2],
  ['Mind > Forgetfulness', 'Aurum met', 1],
  ['Fever > Heat, burning', 'Baptisia', 2], ['Mind > Delirium', 'Baptisia', 3],
  ['Chest > Palpitation', 'Cactus', 2],
  ['Generalities > Weakness, prostration', 'Camphora', 3], ['Fever > Chill, shivering', 'Camphora', 3],
  ['Ear > Earache', 'Capsicum', 2], ['Fever > Chill, shivering', 'Capsicum', 2],
  ['Skin > Boils, abscess', 'Carbo animalis', 2], ['Generalities > Worse evening or night', 'Carbo animalis', 2],
  ['Head > Headache, one-sided right', 'Chelidonium', 2], ['Mouth > Taste, bitter', 'Chelidonium', 3],
  ['Generalities > Better from warmth', 'Chelidonium', 2],
  ['Mind > Irritability', 'Cina', 3], ['Abdomen > Pain, colic', 'Cina', 2],
  ['Stomach > Craving, sweets', 'Cina', 2],
  ['Female > Menses, too late', 'Cimicifuga', 2],
  ['Head > Vertigo', 'Conium', 2], ['Generalities > Weakness, prostration', 'Conium', 2],
  ['Chest > Palpitation', 'Digitalis', 2], ['Stomach > Nausea', 'Digitalis', 2],
  ['Abdomen > Pain, colic', 'Dioscorea', 2],
  ['Fever > Fever with thirst', 'Eupatorium perf', 3], ['Generalities > Weakness, prostration', 'Eupatorium perf', 2],
  ['Generalities > Worse from heat', 'Fluoric acid', 3],
  ['Head > Headache from sun or heat', 'Glonoinum', 3], ['Head > Pain, throbbing', 'Glonoinum', 3],
  ['Generalities > Better from cold', 'Glonoinum', 2],
  ['Mind > Restlessness', 'Kali brom', 2], ['Sleep > Sleeplessness', 'Kali brom', 3],
  ['Mouth > Tongue, coated white', 'Kali mur', 3], ['Nose > Discharge, thick stringy', 'Kali mur', 2],
  ['Throat > Swallowing, painful', 'Kali mur', 2],
  ['Nose > Discharge, thick stringy', 'Kali sulph', 2], ['Generalities > Worse evening or night', 'Kali sulph', 2],
  ['Teeth > Toothache, worse warmth', 'Kreosote', 2], ['Fever > Sweat, night', 'Kreosote', 2],
  ['Head > Pain, throbbing', 'Lac defloratum', 2], ['Rectum > Constipation', 'Lac defloratum', 2],
  ['Chest > Palpitation', 'Lilium tigrinum', 3], ['Female > Menses, too early', 'Lilium tigrinum', 2],
  ['Mind > Irritability', 'Lilium tigrinum', 3],
  ['Abdomen > Pain, colic', 'Mag carb', 3], ['Mind > Irritability', 'Mag carb', 3],
  ['Teeth > Teeth, grinding', 'Mag carb', 2],
  ['Stomach > Vomiting', 'Natrum phos', 2], ['Abdomen > Flatulence, bloating', 'Natrum phos', 2],
  ['Stomach > Nausea', 'Petroleum', 2], ['Generalities > Worse from cold, damp', 'Petroleum', 2],
  ['Throat > Swallowing, painful', 'Phytolacca', 3], ['Skin > Boils, abscess', 'Phytolacca', 2],
  ['Rectum > Diarrhoea', 'Podophyllum', 3], ['Generalities > Worse morning', 'Podophyllum', 2],
  ['Skin > Eruptions, itching', 'Psorinum', 3], ['Fever > Chill, shivering', 'Psorinum', 3],
  ['Mind > Restlessness', 'Pyrogenium', 2], ['Generalities > Better from motion', 'Pyrogenium', 2],
  ['Head > Headache, one-sided right', 'Sanguinaria', 3], ['Head > Headache from sun or heat', 'Sanguinaria', 2],
  ['Urine > Urine, burning', 'Sarsaparilla', 2], ['Urine > Urine, scanty', 'Sarsaparilla', 2],
  ['Cough > Cough, loose rattling', 'Senega', 3], ['Chest > Oppression of chest', 'Senega', 2],
  ['Nose > Sneezing, frequent', 'Squilla', 2], ['Cough > Cough, dry', 'Squilla', 2],
  ['Generalities > Weakness, prostration', 'Stannum met', 3], ['Cough > Cough, with expectoration', 'Stannum met', 2],
  ['Generalities > Weakness, prostration', 'Tabacum', 3], ['Stomach > Vomiting', 'Tabacum', 3],
  ['Mind > Restlessness', 'Tarentula', 3], ['Mind > Loquacity', 'Tarentula', 2],
  ['Mind > Restlessness', 'Tuberculinum', 2], ['Fever > Sweat, night', 'Tuberculinum', 3],
  ['Respiration > Breathing, difficult', 'Tuberculinum', 2], ['Generalities > Worse from cold, damp', 'Tuberculinum', 2],
];
